### ISSUE TITLE
Provide setters for all properts of ContainerConfiguration

### ISSUE THREAD

**Issue by georgringer** [b13/container#103]
It would be nice to have setters for all properties of `ContainerConfiguration`. 

Currently I need to do something like this

```php
$container = new \B13\Container\Tca\ContainerConfiguration(
        'container-tabs',
        'Tab Container',
        'Container Element mit Tabs',
        [
            [
                [
                    'name' => 'Inhalt',
                    'colPos' => 201
                ]
            ]
        ],
    );
    $container->setIcon('container-tabs');
```

but I am really bad with those big constructur injections.
So I would prefer something 

```php
$container = new \B13\Container\Tca\ContainerConfiguration('container-tabs);
$container->setTitle('Tab Container');
...
```

**Comment by achimfritz** [comment]
hm, all constructure arguments are required for a container, `$container = new \B13\Container\Tca\ContainerConfiguration('container-tabs);` does not make any sence.

**Comment by ervaude** [comment]
Introducing setters and removing required options from the constructor would lead to invalid ContainerConfiguration objects, which is very bad.

You can look forward to PHP 8 and named parameters ;)

**Comment by georgringer** [comment]
Imo the 3rd argument (configuration) could easily be optional but I am fine with that. Feel free to close
