### ISSUE TITLE
Loosing child records on copying

### ISSUE THREAD

**Issue by buepro** [b13/container#108]
# Environment
- TYPO3 10.4
- container 1.2.0
- container_elements 1.1.0

# Error description
Copying container elements with child records isn't reliable. Sometimes it work and sometimes the child records are mixed up or missing. Observations:
- When pasting container elements with child contents to a blank page child contents are available
- When pasting container elements with child contents to a page that already has a content element child contents are not available. This is true when pasting takes place after the existing content element. When it is pasted before the existing content element the child contents are available.
- When pasting container elements with child contents having images (FAL references) these content elements get references to additional images (e.g. when the original child element has one image the pasted pne has two images)

**Comment by opi99** [comment]
Question: Do you also use content_defender ?

**Comment by buepro** [comment]
No, content_defender isn't used.

**Comment by opi99** [comment]
Thanks for feedback, I'm debugging such an issue at the moment on a project with content_defender

**Comment by ulrichmathes** [comment]
> Question: Do you also use content_defender ?

Yes we are.

**Comment by achimfritz** [comment]
thanks for reporting and example, 
Observation 2: got it, pid of children is not updated to pid of container, when copy container after an element on other page. I will care.

**Comment by opi99** [comment]
@achimfritz I'm also debugging in this area at the moment I found this one (it isn't directly this issue but seams to be related) https://github.com/IchHabRecht/content_defender/issues/76 and and added a pull request there.
But this issue persists afterwards but it changes from "only happens by pasting after an element" to "happens everytime when an element is pasted from another page" so it looks like an issue while calculating the parent on the new page.

**Comment by achimfritz** [comment]
Observation 2 is fixed by PR

Can anybody give an exact example how the error in "Observation 3" occures? (for me all seems work fine)

**Comment by opi99** [comment]
@achimfritz Thanks, this works for me.

**Comment by opi99** [comment]
Till yet, I also didn't get "Observation 3" and I'm hardly testing.

**Comment by buepro** [comment]
The issue could be reproduced by pasting a container element with children on a page where there are already container elements. By pasting it below the already available content elements the child element gets lost or isn't shown (observation 2). When adding a new child element just the newly added child element is shown. Copying and pasting this container to a new page where no content elements are present, the newly inserted container element shows two children: The one originally copied and not shown on the first pasted container element and the one added to the first pasted container element.

It looks like with fixing Observation 2 the issue gets resolved.

**Comment by achimfritz** [comment]
so i close this issue
