### ISSUE TITLE
Dataprocessing column children

### ISSUE THREAD

**Issue by rupasix** [b13/container#110]
Hello!
Can i somehow process children of column using "dataProcessing"? I imagine it would work like DatabaseProcessor example from docs: https://docs.typo3.org/m/typo3/reference-typoscript/master/en-us/ContentObjects/Fluidtemplate/DataProcessing.html#databasequeryprocessor

I tried something like that, without success:
```
tt_content.wrapper < lib.contentElement
tt_content.wrapper {
  templateName = Wrapper
  templateRootPaths.10 = EXT:awesome_ext/Resources/Private/Templates/Grid/
  dataProcessing {
    200 = B13\Container\DataProcessing\ContainerProcessor
    200 {
      colPos = 200
      as = children
      dataProcessing.10 = TYPO3\CMS\Frontend\DataProcessing\FilesProcessor
      dataProcessing.10 {
        references.fieldName = image
        as = image
      }
    }
  }
}
```

**Comment by achimfritz** [comment]
this is not implemented on the ContainerProcessor. What is your Use Case for this requirement? why not use the `renderedContent` of the the children? There all dataProcessing of the Content Elements are applied. Required DataProcessors should connect to the Content Element direct, so rendering behaviour not matter if the Conent-Element is rendered inside a Container, or outside a Container.

**Comment by rupasix** [comment]
Hello!, Thanks for explanation. Sometimes I need to render inner content differently. Quick example, Accordion with bodytext and image: 
- Container with one column 
- ext:content_defender allows only CType textpic
- i want to render image (if exists) on right and text on left and additionaly show smaller image in accordion header, something like that (:designer-face:):
![image](https://user-images.githubusercontent.com/9860558/102478403-d6835700-405d-11eb-9117-75b1157674ea.png)

I don't want to create additional tt_content[layout] for textpic and write additional conditions in overrided templates for FSC because that particular layout only make sense when pressed in that particular Container "Accordion". I also want to avoid manually register new CType, installing mask or other alternatives. Just simple accordion with one type of content. I hope you get my point.

**Comment by rs-vonholten** [comment]
Hello, I would like to use this feature as well. So maybe you could merge this PR?
