### ISSUE TITLE
failure in BE-field "colpos" when both, "container" AND "gridelements" are activated

### ISSUE THREAD

**Issue by kurtkk** [b13/container#115]
I want to suggest that #gridelements should be listed in under '**conflicts**' in ext_emconf.php and in composer.json. #gridelements and #container don't work together. In #container CEs the "colpos" (e.g. 101, 102 ...) would not be accepted.

**Comment by PeaceSfiSh** [comment]
The reason for this is that the EXT:container ItemProcFunc for 'cosPos' is overridden by EXT:gridelements or the other way around.
To make it compatible I created an own ItemProcFunc for 'colPos', but maybe it's not bulletproof in the current state.

```
use TYPO3\CMS\Core\Utility\ExtensionManagementUtility;
use TYPO3\CMS\Core\Utility\GeneralUtility;

class ItemProcFunc
{
    /**
     * @param array $parameters
     */
    public function colPos(array $parameters): void
    {
        $row = $parameters['row'];

        if (ExtensionManagementUtility::isLoaded('gridelements') && (int)$row['tx_gridelements_container'] > 0) {
            /** @var \GridElementsTeam\Gridelements\Backend\ItemsProcFuncs\ColPosList $gridelementsColPos */
            $gridelementsColPos = GeneralUtility::makeInstance(\GridElementsTeam\Gridelements\Backend\ItemsProcFuncs\ColPosList::class);
            $gridelementsColPos->itemsProcFunc($parameters);
            return;
        }

        /** @var \B13\Container\Tca\ItemProcFunc $containerColPos */
        $containerColPos = GeneralUtility::makeInstance(\B13\Container\Tca\ItemProcFunc::class);
        $containerColPos->colPos($parameters);
    }
}
```
Feel free to comment or adopt. It's also possible to create an additional extension to solve the 'colPos' incompatibility.

**Comment by achimfritz** [comment]
i close this issue, if you need install EXT:container and EXT:gridelements together, you have to create you own ItemProcFunc like described above.
