### ISSUE TITLE
Missing feature for EXT:news or module: list

### ISSUE THREAD

**Issue by iammati** [b13/container#120]
Hello there,

I've got the following use-case:
in EXT:news there's the contentElements-field where I'd like to use a 2-cols-container - but this is sadly not possible since it provides a plus-button which only triggers the inline-record to be toggled as-in an accordion-like-ish behaviour.
Would like to see something similiar to EXT:gridelements where it's possible to add records also inside the list-module, would be super helpful.

Also this could get handy when editing the container-record inside the page-module directly and you would like to see which records are inside this container you're editing atm.

![image](https://user-images.githubusercontent.com/41418763/104903456-531c9480-5980-11eb-8d94-59445ce21758.png)

**Comment by iammati** [comment]
Is there maybe a way to do it on my own? I'd like to build it but I've no knowledge about BackendLsyout Grids or displaying inline records.. any idea maybe?

**Comment by achimfritz** [comment]
Hi @iammati ,
This is not possible by Design. The EXT:container is restricted to Page-Module only. It has only one Relation Field (tx_container_parent) to reduce complexity and to bring most stability to Workspace and Multilanguage Issues.

My Workaround would be: add an new Field to the News Record "Content Elements Left".

**Comment by timdreier** [comment]
Just in case anyone comes over this issue:
I created a extension which extends container to bring back this functionality: [https://github.com/team23/t23_inline_container/](https://github.com/team23/t23_inline_container/)
