### ISSUE TITLE
TYPO3 11 Compatibility

### ISSUE THREAD

**Issue by andyhausmann** [b13/container#122]
Just tested EXT:container and EXT:container_example in a new TYPO3 11 Instance. 

Unfortunately none of the Custom Elements do appear in the New Content Element Wizard as well as no errors in sys_log or within /var/log/.
Just nothing happens.

Ideas?

**Comment by achimfritz** [comment]
Hi @andyhausmann , we are working on V11 support, will come soon

**Comment by andyhausmann** [comment]
Works for me!
