### ISSUE TITLE
Losing child records when pasting in "List" module

### ISSUE THREAD

**Issue by sebkln** [b13/container#126]
If you copy a container with containing content elements, you can only successfully paste this whole group of content in the "Page" backend module. When switching to the "List" module, only the container will be inserted.

## Environment
- `typo3/cms-base-distribution` 10.4.12
- `b13/container` 1.2.0
- `b13/container_example` 1.0.0
- composer
- fresh installation, no other third-party extensions except `helhum/typo3_console`

## Steps to reproduce
1. Create a container with some content.
2. Copy the container into the clipboard. It makes no difference in which module you copy the container; the result will be the same.
3. Use the "Page" module to paste into a page: successful.
4. Paste the very same clipboard content in the "List" module: all container content is missing.

I also tried it with current `b13/container:dev-master` (and a custom container configuration), with the same result.

**Comment by achimfritz** [comment]
sorry, we only support Page-Module.
