### ISSUE TITLE
Clicking on the plus-buttons in the list module throws JS-error

### ISSUE THREAD

**Issue by iammati** [b13/container#127]
Clicking on one of the marked plus-buttons throws the following JavaScript error in console:

![image](https://user-images.githubusercontent.com/41418763/107434436-14b36900-6b2b-11eb-9865-94d047b89f84.png)
![image](https://user-images.githubusercontent.com/41418763/107434511-272da280-6b2b-11eb-885a-6f348efed972.png)

I assume it's or was just a test / WIP etc.
Is therefor something planned in future?

**Comment by achimfritz** [comment]
supporting container Elements in news Record is not planned. But i do not know, why the "+" Button is rendered in the news Record. With "Fluid based page module" Feature is enabled, the "+" Buttons are not rendered. TYPO3 V11 has only the Fluid base page module, so we do not care, sorry.

**Comment by fnagel** [comment]
Related to #120
