### ISSUE TITLE
Content defenders' maxitems does not count per container but per colPos

### ISSUE THREAD

**Issue by susannemoog** [b13/container#131]
Hey container team,

With the following minimal container configuration:

```
                   [
                        'name' => 'elements',
                        'colPos' => 212,
                        'maxitems' => 3,
                    ],
```
I can add one container with 3 elements or two containers with 1 and 2 elements, however, I cannot add multiple containers with 3 elements per container.
It seems as if maxitems is interpreted on colPos base and not on container base.

If you need more info, please ping me :)

**Comment by achimfritz** [comment]
OMG!, cannot work at all, thanks for reporting,

**Comment by achimfritz** [comment]
XClass Solution : https://github.com/b13/container/commit/a57ddffd0d054a6e6572fce555b6d0f146b0da55?branch=a57ddffd0d054a6e6572fce555b6d0f146b0da55&diff=unified
