### ISSUE TITLE
copy only works in list view - paste only works in page view

### ISSUE THREAD

**Issue by bh-teufels** [b13/container#136]
Hello i have the Problem that copy of
Content Elements (inside Container) and whole Container only works if i do the copy in list view and the paste in page view

Typo3 10.4.13
container 1.2.0

**Comment by chriskrj** [comment]
I cannot reproduce the error. Which php version are you using and is there an error in the backend? Maybe also in the console?

**Comment by achimfritz** [comment]
@bh-teufels cat you give more Information about your setup, and why you cannot copy the Elements in Page-Module?

**Comment by achimfritz** [comment]
@bh-teufels i close this issue, please reopen if problem still exists
