### ISSUE TITLE
No CE's in container shown, whenn set language to 'all'.

### ISSUE THREAD

**Issue by stephangrass** [b13/container#141]
I would like to display the container and its contents in all languages ​​in the default language. For this purpose I have selected "All" under language in the CE. The container element is displayed in all languages, but the CEs within are not. Language is also set to "All" for the CEs in the container.

Dagging the content element's out of the contaier, they will be displayed in all languages.

A bug? Missing configuration?

**Comment by achimfritz** [comment]
sorry, this is not implemented, and will also not be supported in future

**Comment by stephangrass** [comment]
Thank you for the information. It's not what I wanted to hear ... Is it that difficult to implement?

**Comment by achimfritz** [comment]
this will bloat our code/SQL-Queries, we never use language all in our projects.

**Comment by stephangrass** [comment]
ok, thanks ...
In our case we have 6 languages ​​and pages / content-elements such as downloads, links, partners and also news, which should be displayed everywhere in the default language. Then we just have to look for another solution in this case.
