### ISSUE TITLE
Translatable labels for container configuration

### ISSUE THREAD

**Issue by maddy2101** [b13/container#144]
Hi there, 

first of all: thank you so much for this extension. It works great, we love using it.

There is one thing I can't figure out and hope for guidance: we would want to provide container labels to our editors in their own language, according to the chose BE Language, but it does not seem to work. This is an example config:

```
    new \B13\Container\Tca\ContainerConfiguration(
        'accordion-grid', // CType
        'LLL:EXT:site_package/Resources/Private/Language/locallang.xlf:container.accordion_grid.title',
        'LLL:EXT:site_package/Resources/Private/Language/locallang.xlf:container.accordion_grid.description',
        [
            [
                ['name' => 'LLL:EXT:site_package/Resources/Private/Language/locallang.xlf:container.accordion_grid.name', 'colPos' => 301]
            ],
        ],
    )
```
    
the locallang.xlf file exists at the very position.
But in BE, the container module is now labeled only with the column number, no title or description are given.
    
Did I do something wrong, or does the configuration not support labels?
    
Kind regards
Anja

**Comment by chriskrj** [comment]
What does your language file look like? Overwriting the label and description fields works for me.

```xlf
      <trans-unit id="container.gridcol1main">
        <source>GridCol1Main</source>
        <target>Raster 1 Spalte</target>
      </trans-unit>
```
```php
<?php

\TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance(\B13\Container\Tca\Registry::class)->configureContainer(
    (
    new \B13\Container\Tca\ContainerConfiguration(
        'gridcol1main',
        'LLL:EXT:nc_provider_main/Resources/Private/Language/de.locallang.xlf:container.gridcol1main',
      )
    )
);
```

maybe check if the target Language in the xliff file ist correct and that your language file name is like `de.locallang.xlf`

**Comment by achimfritz** [comment]
@maddy2101 Hi Anja, this should work, where do you miss the labels? (in the New Content Element Wizard?) What Versions do you use (TYPO3, EXT:container), EXT:content_defender installed (Version?)? Fluid based page module enabled?

**Comment by erredeco** [comment]
I cannot confirm this issue with version 1.2.0; I am using xlf labels as label, description an name of the columns

**Comment by maddy2101** [comment]
all right, I will try again and report back.

**Comment by achimfritz** [comment]
@maddy2101 i close this issue, please reopen if problem still exists
