### ISSUE TITLE
[FEATURE] use registered icon as Icon for the container CE

### ISSUE THREAD

**Issue by erredeco** [b13/container#145]
According to the documentation, the `setIcon` option accepts a string as icon, e.g. 

```
 ->setIcon('EXT:container_example/Resources/Public/Icons/b13-2cols-with-header-container.svg')
```

It would be nice to use an icon registered with `registerIcon` , too.

**Comment by davidsteeb** [comment]
Just tried this, it's already working:

```    ->setIcon('some-icon')```

**Comment by erredeco** [comment]
@davidsteeb yes!! Thank you.

Can we say that at least the documentation could be updated?

**Comment by davidsteeb** [comment]
Yes, of course.

**Comment by davidsteeb** [comment]
Actually, it's already in the documentation :-)

![image](https://user-images.githubusercontent.com/3862523/111888275-6b8a4900-89db-11eb-9ab1-fbd11de04d71.png)

**Comment by erredeco** [comment]
maybe the "string $icon" deceived me but oh, well... silly me.
