### ISSUE TITLE
Multiple unassigned columns in one container doesn't work

### ISSUE THREAD

**Issue by KoenWouters** [b13/container#151]
When i am adding a grid with two empty colPos positions the second one is not rendered in TYPO3.
My goal is to make a 2-8-2 grid visible in the backend. Only the column with colspan 8 may have content.

Config:
![Screenshot 2021-05-03 at 15 58 20](https://user-images.githubusercontent.com/7394260/116885649-69491a80-ac28-11eb-89fb-aa4f27b16dbc.png)

Result:
![Screenshot 2021-05-03 at 15 54 45](https://user-images.githubusercontent.com/7394260/116885685-7403af80-ac28-11eb-80a4-f818ac425725.png)

Goal:
A "no colPos" block on both sides of my text element.

**Comment by achimfritz** [comment]
@KoenWouters 
looks like you did not define a colPos for each column, column 0 and 2 need also a colPos (e.g. 201 and 203)

**Comment by KoenWouters** [comment]
@achimfritz  yes. That's because I do not want an editor to add content in column 0 and 2. I only want them to add content to column 1.

**Comment by achimfritz** [comment]
mh, what is your usecase? i do not understand.

**Comment by KoenWouters** [comment]
I am building a 2-8-2 grid (in the frontend). To show the editors that this column for content is smaller than a default one column grid, i want an empty column on both sides.

I build it with screenshots:
![Screenshot 2021-05-04 at 09 29 08](https://user-images.githubusercontent.com/7394260/116972513-66e3d080-acbb-11eb-866a-cf1900484f2f.png)

**Comment by achimfritz** [comment]
for this usecase please use your own grid-Template (s. https://github.com/b13/container/blob/master/Resources/Private/Templates/Grid.html),  or your own container-Template (https://github.com/b13/container/blob/master/Resources/Private/Templates/Container.html) for BE-View. This can be set by ContainerConfiguration `setGridTemplate` or `setBackendTemplate` (s. README.md). Or do not use a container element, but build your own CE (with own BE/FE-View).

**Comment by KoenWouters** [comment]
So my use case will not be supported?

**Comment by achimfritz** [comment]
Hi @KoenWouters ,

i think this use case is supported, s. https://github.com/b13/container-example/tree/container-issue-151 (https://github.com/b13/container-example/commit/57d8783f8dbbfd49ac4e893c54e1bd8031fae3a7) for example (this works with TYPO3 10 without "fluid based page module" enabled (for fluid based page module you have to set (or add) gridPartialPaths in you container-registry, and create you partials for rendering, s. https://github.com/b13/container/issues/166))

the example ends in 
![2-8-2-container](https://user-images.githubusercontent.com/2152991/137558901-3eb5ee8d-d031-45a1-b8c1-6f38c60642bf.png)

does this help?

**Comment by achimfritz** [comment]
closed due no feedback
