### ISSUE TITLE
[FEATURE] add the option to provide custom "showitem" config

### ISSUE THREAD

**Issue by tpinne** [b13/container#158]
Sometimes a container might need a config option. Currently I build an accordion with this extension. 

```
Outer container = whole accordion
    -> Inner containers = accordion panels
        -> content elements = accordion panel content
```

The outer container might need a checkbox box to toggle grouping mode where only one panel at a time is open.
If there would be an option to provide a custom `showitem` config to `\B13\Container\Tca\ContainerConfiguration` I could easily extend the `tt_content` table with a custom field and show it in the container form for the specific container.

And in the fluid template I could access it (if I'm not mistaken) with either `{data.tx_my_column}` or  `{reocrd.tx_my_column}` depending on the context.

Might be an easy to implement addition as additional optional parameter to the constructor of `\B13\Container\Tca\ContainerConfiguration` with a fallback to the current `showitem` config string.

**Comment by davidsteeb** [comment]
Hi @tpinne,

you can set a `showitem` configuration the same way you would for any other CType, see our blog post with an advanced example:

https://b13.com/blog/flexible-containers-and-grids-for-typo3-part-three

Is this what you're looking for?

**Comment by tpinne** [comment]
Of course, duh. Sometimes the solution is to obvious to see when your in the zone 😂
