### ISSUE TITLE
tx_container_parent LOCALIZED_UID

### ISSUE THREAD

**Issue by rafu1987** [b13/container#159]
Hi there,

Currently I have a container element and in an element inside that container, I'm using the uid of the parent element (container element). That works well with the default language, but if I translate everything (connected mode, didn't try in free mode, but I expect the same outcome), the field tx_container_parent still points to the uid of the container element in the default language.

Is it somehow possible to get the LOCALIZED_UID of the parent element instead?

For now, I got it working with a custom ViewHelper, which fetches the LOCALIZED_UID based on the current language and the uid of the container element in the default language.

**Comment by achimfritz** [comment]
@rafu1987 for what is this required exactly? in Frontend you can use `{data.uid}`(of the container itselfs) for the localized container uid, do not use {child.tx_container_parent}

**Comment by rafu1987** [comment]
@achimfritz I wanted the uid of the translated parent in the child element, but never mind - I changed it to `{data.uid}` for default language and translations. :-)
