### ISSUE TITLE
Backend Exception

### ISSUE THREAD

**Issue by kevin-appelt** [b13/container#161]
After this core change (https://review.typo3.org/c/Packages/TYPO3.CMS/+/69493/) the backend throws an exception:
The Fluid template files "/typo3conf/ext/container/Resources/Private/Partials/PageLayout/Record/Header.html", "/typo3conf/ext/container/Resources/Private/Partials/PageLayout/Record/Header", "/typo3/sysext/backend/Resources/Private/Partials/PageLayout/Record/Header.html", "/typo3/sysext/backend/Resources/Private/Partials/PageLayout/Record/Header" could not be loaded.

/typo3conf/ext/container/Resources/Private/Partials/PageLayout/Record.html
needs to be renamed to
/typo3conf/ext/container/Resources/Private/Partials/PageLayout/RecordDefault.html
in order to work again.

**Comment by juergen-venne** [comment]
This does not fix it for me.
Looking into typo3/sysext/backend/Resources/Private/Partials/PageLayout shows this content in TYPO3 11:
+ Grid
- RecordDefault
  - Footer.html
  - Header.html
  - Preview.html
- Record.html
- ...
Comparing to TYPO3 10:
+ Grid
- Record
  - Footer.html
  - Header.html
  - Preview.html
- Record.html
- ... 
Please note the renamed folder "Record" to "RecordDefault"
To me it looks like an ugly breaking change in sysext/backend. https://review.typo3.org/c/Packages/TYPO3.CMS/+/69493/

So the file Record.html must not be renamed. A solution may be to adapt it's content to the original file in sysext:backend:
Change the calls of 
 <f:render partial="PageLayout/Record/*" to <f:render partial="PageLayout/RecordDefault/*"

**Comment by kimchristiansen** [comment]
I have the same exception after updating from TYPO3 10.4.17 to 10.4.18.

**Comment by bh-teufels** [comment]
same after updating from 10.4.17 to 10.4.18
