### ISSUE TITLE
Use the same colPos in multiple containers with diffrent name

### ISSUE THREAD

**Issue by Xippo** [b13/container#164]
Thanks for sharing and maintainig this Extension :)

My Setup:
TYPO3 10.4.17
Container: 1.3.0
over Composer.

If I implement two containers that share a colPos (200) and I rename the colPos in the second element, the name from the first element is still used. Im not sure if its a bug or bad practice to use the same colPos for diffrent containers. In Gridelements i could share the colPos and setup different names. 
I know this is not Gridelements and im fine when its not intended by design to share colPos

**Comment by achimfritz** [comment]
Hi @Xippo do you use "Fluid based page module" Feature? I think this is already fixed in dev-master with https://github.com/b13/container/pull/143/commits/49e44319be2ed91d5853fc3f3ab9591421870788 (s. also https://github.com/b13/container/issues/142) can you test master-branch?

**Comment by Xippo** [comment]
Hi @achimfritz , thanks for the quick answer. Sorry I had not seen the #142 before, my bed :(. I will test the master an report. It is a new TYPO3 10 instance and I believe the feature is on by default, therefore I think it is active but I will check it. Does the extension support only the new mode?

**Comment by Xippo** [comment]
I have tested the dev-master, there it works like a charm. In the system fluid based page module is enabled. Thx for your help.
