### ISSUE TITLE
InvalidTemplateResourceException Error with Typo3 10.4.18

### ISSUE THREAD

**Issue by bh-teufels** [b13/container#168]
just updated Typo3 from 10.4.17 to 10.4.18 and get Error

#1225709595 TYPO3Fluid\Fluid\View\Exception\InvalidTemplateResourceException
The Fluid template files "/app/web/typo3conf/ext/container/Resources/Private/Partials/PageLayout/Record/Header.html", "/app/web/typo3conf/ext/container/Resources/Private/Partials/PageLayout/Record/Header", "/app/web/typo3/sysext/backend/Resources/Private/Partials/PageLayout/Record/Header.html", "/app/web/typo3/sysext/backend/Resources/Private/Partials/PageLayout/Record/Header" could not be loaded.

**Comment by tehplague** [comment]
Duplicate of #161

**Comment by bh-teufels** [comment]
closed 
continued in [#161](https://github.com/b13/container/issues/161)
