### ISSUE TITLE
PHP 8 warning for `shadowColumnsForNewPlaceholders` in tt_content Override

### ISSUE THREAD

**Issue by o-ba** [b13/container#174]
Using PHP 8 and TYPO3 v11 following warning is triggered in e.g. recordlist:

```
PHP Warning
Core: Error handler (BE): PHP Warning: Undefined array key "shadowColumnsForNewPlaceholders" in /var/www/html/typo3conf/ext/container/Configuration/TCA/Overrides/tt_content.php line 40
```

**Comment by o-ba** [comment]
See https://forge.typo3.org/issues/92497, where this property got removed from core.

**Comment by DenisMir** [comment]
It would be great if a patch new version could be released including this fix.
