### ISSUE TITLE
Update Request handling (PSR-7 and PSR-15)

### ISSUE THREAD

**Issue by vmans** [b13/container#189]
Please update the request handling in

/t3sbootstrap/Classes/EventListener/AssetRenderer/IsInline.php.

Change

```
		if (ApplicationType::fromRequest($GLOBALS['TYPO3_REQUEST'])->isBackend()) {
			return;
		}
```

into

```
		if (($GLOBALS['TYPO3_REQUEST'] ?? null) instanceof ServerRequestInterface
			&& ApplicationType::fromRequest($GLOBALS['TYPO3_REQUEST'])->isBackend()) {
			return;
		}
		
		if (defined('TYPO3_MODE') && TYPO3_MODE === 'BE') {
			return;
		}
```

References:
https://docs.typo3.org/m/typo3/reference-coreapi/9.5/en-us/ApiOverview/RequestHandling/Index.html
https://docs.typo3.org/m/typo3/reference-coreapi/9.5/en-us/ApiOverview/RequestHandling/Typo3Request.html#typo3-request

In my case, I needed this change to make 2FA on the backend login work.

**Comment by jschlier** [comment]
I suggest you open this issue in the [t3solution/t3sbootstrap](https://github.com/t3solution/t3sbootstrap) repository.

**Comment by vmans** [comment]
Sorry, I wasn't paying attention. Thanks ;-)
