### ISSUE TITLE
Paste as reference only creates/link item in default language

### ISSUE THREAD

**Issue by p-view** [b13/container#202]
Page with two languages, in connected mode. Copied a content element  and pasted it as reference on a new page. When i translate the reference the elements in the container are in default language

**Comment by achimfritz** [comment]
@p-view can you please give detail steps to reproduce this behaviour? Is it a container you copied and paste as reference? (has this container already children?), or do you paste a "normal" content element into a container as reference? does this all happens on default language? How do you translate which content element exactly?

**Comment by p-view** [comment]
I create a reference from a container with text elements inside in another site. In both translation modes is this behavior.
I can send you a pm with testlogin for this bug if you want.

**Comment by p-view** [comment]
Hello,
it only happens when the reference comes from another page/pid. If you want
I can give you a test login.
BR

Am Do., 11. Nov. 2021 um 17:52 Uhr schrieb Achim Fritz <
***@***.***>:

**Comment by achimfritz** [comment]
@p-view on my example the reference comes also from another page, you can give me a test login, if you thinks it helps

**Comment by achimfritz** [comment]
Hi @p-view, any news? else i will close this issue
