### ISSUE TITLE
Timeframe on when to get the next tagged release? (TYPO3 11 + PHP 8.0)

### ISSUE THREAD

**Issue by DenisMir** [b13/container#203]
I'd like to kindly ask if there is a timeframe on when there could be a release for the next tagged version? Since the last release a lot of improvements/bugfixes would be nice to have especially in the context of TYPO3 11LTS and PHP 8.0. E.g. the current packagist version 1.3.1 does trigger warnings due to the changed PHP error level in PHP 8.0. This results in TYPO3 exceptions while developing in the Debug Preset. (`'SYS/exceptionalErrors' => 12290`)

**Comment by achimfritz** [comment]
just released 1.4.0

**Comment by DenisMir** [comment]
Awesome thank you very much!
