### ISSUE TITLE
Change Container Configuration at runtime to enricht allowed list (CType, list_type)

### ISSUE THREAD

**Issue by JBlocks** [b13/container#206]
We need a possibility to register a content element or a container when activating an extension ACME to an existing container in the allowed List (CType, list_type).

**Real world example**
I have a base extension in which a container "container_foo" exists. If the extension ACME is now installed, the content elements (CType) defined in, must be allowed in the "container_foo" container of EXT:base.
In case of Gridelements, this could be solved in the classic way using `tx_gridelements_backend_layout: = addToList (acme_content_bar)`.

Tried it with an ugly TCA overrides hack .... it works, but it might be wrong ... :wink:

Proof version 1:
```
$grid = \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance(\B13\Container\Tca\Registry::class)
    ->getGrid('container_foo');
if (isset($grid[0][0]['allowed']['CType'])) {
    $grid[0][0]['allowed']['CType'] .= ',acme_content_bar';
    $GLOBALS['TCA']['tt_content']['containerConfiguration']['container_foo']['grid'] = $grid;
}
```

Proof version 2:
```
$registry = \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance(\B13\Container\Tca\Registry::class);
$cType = 'container_foo';
if ($registry->isContainerElement($cType)) {
    $containerConfig = $GLOBALS['TCA']['tt_content']['containerConfiguration'][$cType];
    $containerConfig['grid'][0][0]['allowed']['CType'] .= ',acme_content_bar';
    $registry->configureContainer(
        (
        new \B13\Container\Tca\ContainerConfiguration(
            $cType,
            $containerConfig['label'],
            $containerConfig['description'],
            $containerConfig['grid']
        )
        )
            ->setIcon($containerConfig['icon'])
            ->setSaveAndCloseInNewContentElementWizard($containerConfig['saveAndCloseInNewContentElementWizard'])
            ->setGroup($containerConfig['group'])
            ->setRegisterInNewContentElementWizard($containerConfig['registerInNewContentElementWizard'])
            ->setBackendTemplate($containerConfig['backendTemplate'])
            ->setGridPartialPaths($containerConfig['gridPartialPaths'])
    );
}
```
No public function was found in the Container Registry to solve this use case.

**Comment by achimfritz** [comment]
sorry, this would not be possible, because the container-Registration do not parse any pageTSConfig, because it knows nothing about any page ID. The Configuration is saved fixed at build time in the `$GLOBALS['TCA']`

Register your Container in your Site-Extension, your Site-Extension should know every Extension installed on your System, and can do an appropriate Configuration

**Comment by achimfritz** [comment]
think about `addToAllTCAContainerTypes` similar to `addToAllTCATypes` to modify `$GLOBALS['TCA']['tt_content']['containerConfiguration'][<CType>]['grid']` (needs not Page-TS ..., and no page ID)

**Comment by JBlocks** [comment]
> think about `addToAllTCAContainerTypes` similar to `addToAllTCATypes` to modify `$GLOBALS['TCA']['tt_content']['containerConfiguration'][<CType>]['grid']` (needs not Page-TS ..., and no page ID)

That sounds really good! thanks

**Comment by zenoussi** [comment]
> > think about `addToAllTCAContainerTypes` similar to `addToAllTCATypes` to modify `$GLOBALS['TCA']['tt_content']['containerConfiguration'][<CType>]['grid']` (needs not Page-TS ..., and no page ID)
> 
> That sounds really good! thanks

Hi @JBlocks,
I'm facing the same problem. Can you post your sample code for us integrators?

Many Thanks
Ulli

**Comment by achimfritz** [comment]
i would suggest to override the whole configuration
