### ISSUE TITLE
Is it somehow possible to pass data to children?

### ISSUE THREAD

**Issue by tpinne** [b13/container#210]
Hi,

I have container which only allow one type content as children. But they can have different outputs/layouts. But they may not vary inside a container. So all children of a container must have the same layout. But it can be different between containers.

Ideally I would like to define the layout on the container and pass that value down to each child. Looking at the code I didn't found a possibility to achieve my goal.

And I don't want to rely on the editors to select the same layout on each child separately. It's error prone and makes switching the layout at a later point a tedious task.

I hope there is something like this wish on the roadmap :)

**Comment by rupasix** [comment]
In these cases, I handle the content of the children inside the parent, it's easiest way. If you absolutely want to condition it from the child's template level, this dataProcessor can propably help you to get data of parent container: https://github.com/benjaminkott/bootstrap_package/blob/master/Classes/DataProcessing/ContainerContextProcessor.php

**Comment by tpinne** [comment]
I'll give the DataProcessor idea a try. Sounds like I could the result I need with it. Handling the children inside the parent is not ideal for me, because the children might also appear independently outside that container

**Comment by tpinne** [comment]
I used the DataProcessor approach and it works like a charm. Thx.
