### ISSUE TITLE
Nice to have feature - Flexfoms for container elements

### ISSUE THREAD

**Issue by paulilea** [b13/container#214]
Hello.
This is not really an issue, more of a feature request. I think it would be nice to have the possibility to extend the registered the container elements with custom flexform fields. I know it's possible to implemented a custom solution for this by manipulating the TCA configuration after the containers have been registered but it would be nice to have this available out-of-the-box. 
For whoever is interested I've created a simple [patch file](https://gist.githubusercontent.com/paulilea/1cd91424712148cb87ad9fd9b58eedfd/raw/efa57175c9e48ab9b9be9d1cf638a7c5525b46a5/addFlexformConfigurationToContainerElements.diff) for the current version (1.4.2) which can be applied using `cweagans/composer-patches`.
Afterwards, the feature can be used by specifying the flexform xml file for the Container configuration object at the registration step.
```
 \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance(\B13\Container\Tca\Registry::class)->configureContainer(
    (
        new \B13\Container\Tca\ContainerConfiguration(
            'container-with-flexform-example',
            'Container with Flexform example',
            '',
            // ... grid configuration
        )
    )
    ->setFlexformDS('FILE:EXT:your-extension-key/Configuration/FlexForms/flexform_file.xml')
)
```
Now your flexform fields should be visible in the Container element's form and the rendering TS can be adjusted to have the flexform data in the Fluid template accessible using the `flexform` (or any custom) variable name.
```
tt_content.container-with-flexform-example < lib.containerElement
tt_content.container-with-flexform-example {
    # ... your template configuration
    dataProcessing {
        # ... grid children configuration
        999 = B13\Container\DataProcessing\FlexformProcessor
        999 {
            as = flexform
        }
    }
}
```

**Comment by the-andyman** [comment]
I would really like to use flexforms in container, but unfortunately the patch does not work for me. 
Would it be possible to make the changed files available elsewhere?

**Comment by Xippo** [comment]
HiHo,
you can simply add the flexform to your content element and use the Flexform DataProcessor shipped by the core in TYPO 11. (< 11 you need your own, but its easy to backport and there are some in the wild to find).
like so:
```php
\TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance(\B13\Container\Tca\Registry::class)->configureContainer(
    (
        new \B13\Container\Tca\ContainerConfiguration(
            '2col-33-66', // CType
            'Container mit 2 Spalten 33%|66%', // label
            '', // description
            [
                [
                    ['name' => 'linke Spalte', 'colPos' => 20],
                    ['name' => 'rechte Spalte', 'colPos' => 21],
                ],
            ] // grid configuration
        )
    )
    ->setIcon('EXT:EXTKEY/Resources/Public/Icons/33-66.png')
);
$GLOBALS['TCA']['tt_content']['types']['2col-33-66']['showitem'] .= 'pi_flexform;YOURLABEL,';

// add Flexform
\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addPiFlexFormValue(
    '*',
    'FILE:EXT:EXTKEY/Configuration/FlexForms/colContainerSettings.xml',
    '2col-33-66'
);
```
```
tt_content.2col-33-66 {
    templateName = 2col-33-66
    templateRootPaths.10 = EXT:EXTKEY/Resources/Private/Templates/Extensions/Container/Templates/
    partialRootPaths.10 = EXT:EXTKEY/Resources/Private/Templates/Extensions/Container/Layouts/
    layoutRootPaths.10 = EXT:EXTKEY/Resources/Private/Templates/Extensions/Container/Layouts/
    dataProcessing {
        20 = B13\Container\DataProcessing\ContainerProcessor
        20 {
            colPos = 20
            as = childrenLeft
        }
        21 = B13\Container\DataProcessing\ContainerProcessor
        21 {
            colPos = 21
            as = childrenRight
        }
        // Core Processing is available >= TYPO11
        101 = TYPO3\CMS\Frontend\DataProcessing\FlexFormProcessor
    }
}
```
Greetings

**Comment by linawolf** [comment]
If you want to have it on the first tab, try:

```

\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addToAllTCAtypes(
    'tt_content',
    'pi_flexform;Container Options',
    '2col-33-66',
    'after:header'
);

```
instead of ` $GLOBALS['TCA']['tt_content']['types']['2col-33-66']['showitem'] .= 'pi_flexform;YOURLABEL,';`

**Comment by NJADA-JJ** [comment]
> If you want to have it on the first tab, try:
> 
> ```
> 
> \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addToAllTCAtypes(
>     'tt_content',
>     'pi_flexform;Container Options',
>     '2col-33-66',
>     'after:header'
> );
> ```
> 
> instead of ` $GLOBALS['TCA']['tt_content']['types']['2col-33-66']['showitem'] .= 'pi_flexform;YOURLABEL,';`

Exactly what i was trying to do myself!

Thanks a lot!

**Comment by paulilea** [comment]
@achimfritz sure.
