### ISSUE TITLE
Invalid value Error in colPos  while adding contents inside a container element

### ISSUE THREAD

**Issue by shilpajh** [b13/container#222]
Hi,

I tried to use container extension in typo11, but while adding contents inside a container grid ,invalid colPos error occurs.
see screenshot attached.

Anyone help me please...
<img width="514" alt="container" src="https://user-images.githubusercontent.com/45961213/147647352-9c372a9c-704a-4350-ab74-61ca0f49dee1.PNG">

**Comment by achimfritz** [comment]
Hi @shilpajh do you have any other "grid-extensions" (like gridelements, flux, etc.) installed? (or anything else, modifies
`$GLOBALS['TCA']['tt_content']['columns']['colPos']['config']['itemsProcFunc']`
)

**Comment by achimfritz** [comment]
@shilpajh any news? else i will close this issue

**Comment by shilpajh** [comment]
Hi @achimfritz 
Grid element was installed . Now it is working fine. Thank you.
