### ISSUE TITLE
colSpan does not work as expected in grid configuration with php8 and TYPO3 11.5LTS

### ISSUE THREAD

**Issue by svenignor** [b13/container#231]
Hello,

not sure if there is a real issue...

I think it's easier to understand with a screenshot of what is happening:
![image](https://user-images.githubusercontent.com/13981370/151715182-a6f8c26b-20ac-4738-9978-3f51b2637730.png)

In container configuration a "colspan" is set. Debug shows all data as expected. -> The layout doesn't fit the settings.

Unfortunately, I didn't find the right place to fix it. 

Any hint for me to fix this?

**Comment by svenignor** [comment]
![image](https://user-images.githubusercontent.com/13981370/151717422-5f0aeada-b6a4-4e01-80d4-c336e24f3de5.png)

**Comment by svenignor** [comment]
Not sure what happened but with 11.5.6 and container 1.5.0 it works. Thank you very much.

**Comment by SvenJuergens** [comment]
hmmm, same problem here with TYPO3 11.5.6, PHP 7.4 and installed with ExtensionManager colspan is always "1"

**Comment by spharion88** [comment]
Had the same issue, but the solution is really simple and not related to TYPO3 or PHP Version, you just have to switch form language to column mode:

```php
public function getColSpan(): int
{
   if ($this->context->getDrawingConfiguration()->getLanguageMode()) {
      return 1;
   }
   return $this->colSpan;
}
```

**Comment by tomashavner** [comment]
One rendering for the column view and a different one for language view?! Really bad UX if you ask me. Could you please change this.
Tomas
