### ISSUE TITLE
Content element not visible if language is set to All Languages [-1]

### ISSUE THREAD

**Issue by Scopestyle** [b13/container#237]
TYPO3 version 10.4.25
Container version 1.5.0
Behaviour tested on multiple projects.

**Problem:**
On a multilanguage TYPO3 installation, whenever a content element in a container is set to _All Languages [-1]_ this content element disappears from the container. Showing this container as empty in the Page view. 

Does anyone have a solution for this?

**Comment by sebastianstein** [comment]
I can confirm this problem.

**TYPO3:** 10.4.26
**Container:** 1.5.0

I assume that this problem is caused by _container/Classes/Domain/Factory/PageView/Frontend/ContainerFactory.php:102_. 
It is still the sys_langauge_uid 0 used even if the setting is set to -1 (all languages).

**Comment by achimfritz** [comment]
yes, sys_language_uid=-1 is not implemented/not supported. The Extension has a strict language policy (either a container is connected or free mode). We decided to not support -1,  focus is on stability and integrity of container and container-children CE.

**Comment by achimfritz** [comment]
closed due sys_language_uid=-1 is not supported

**Comment by wolfgang007** [comment]
@sebastianstein & @Scopestyle how do you fix that problem finally?

thx for your response

**Comment by Scopestyle** [comment]
> @sebastianstein & @Scopestyle how do you fix that problem finally?
> 
> thx for your response

I ended up not using 'All Languages' in Container, but translate them individually.
