### ISSUE TITLE
Use saveAndClose for new content element wizard on "simple" container items

### ISSUE THREAD

**Issue by davidsteeb** [b13/container#24]
It would be nice to make use of the new "saveAndClose" setting for the new content element wizard in v10 on automatic container registration. 

As long as there are no additional, custom "showitems" settings it can be assumed that the container is only used as a means to create content areas to add child elements. In this case, the "saveAndClose" setting could be set to "true" by default.

see also: #23

**Comment by ervaude** [comment]
Resolvedw ith #30
