### ISSUE TITLE
Screen is frozen when changing Ctype in backend in a container

### ISSUE THREAD

**Issue by xbouillet** [b13/container#243]
Hello,

We use container 1.5.0 with a TYPO3 11.5.6.

In backend, on a container, if we want to change the Ctype to use another container, we have a bug. Screen is frozen like a javascript alert.

Any idea ?

Thanks

**Comment by achimfritz** [comment]
Hi @xbouillet , mh, cannot reproduce, can you give more informations? (your container-config? PHP-Version?, Dump of tt_content table this error occurs? EXT:content_defender installed? other extensions?)

**Comment by achimfritz** [comment]
Hi @xbouillet , any news? else i will close the issue

**Comment by achimfritz** [comment]
closed due no feedback
