### ISSUE TITLE
Generate release notes

### ISSUE THREAD

**Issue by mbrodala** [b13/container#250]
Right now the [release notes](https://github.com/b13/container/releases/tag/1.6.0) seem to be handcrafted:

![image](https://user-images.githubusercontent.com/5037116/164047774-7a9b2778-24a5-40f6-9d2b-5f6045720df0.png)

Instead it would be easier and way more useful if they where [generated automatically](https://dev.to/github/how-to-automatically-generate-release-notes-for-your-project-2ng8). Especially since this automatically uses all merged PRs, links them and even mentions all authors.

**Comment by achimfritz** [comment]
used "Autogenerate" for Release Notes (Update 1.6.0, and New 1.6.1), thanks for hint

**Comment by mbrodala** [comment]
Beautiful: https://github.com/b13/container/releases/tag/1.6.1

Thanks a lot. :+1:
