### ISSUE TITLE
FEATURE REQUEST: Add complete tt_content header palette

### ISSUE THREAD

**Issue by clivebeckett** [b13/container#253]
It would be great to have the complete default tt_content header palette available instead of just the header field. After all you don’t have to use it but at least you’d have the option. The default palette I’m talking about contains the following fields:
- header
- header_layout
- date
- header_link
- subheader

It should actually be fairly simple to add:

in `B13\Container\Tca\Registry` (/Classes/Tca/Registry.php) replace line 57:
```
header;LLL:EXT:frontend/Resources/Private/Language/locallang_ttc.xlf:header.ALT.div_formlabel,
```
with
```
--palette--;;headers,
```

Obviously the options need to be added to the templates – but at least it wouldn’t break anything for people using their own templates.

Thanks for considering :)

**Comment by achimfritz** [comment]
Hi @clivebeckett you can always override any TCA Settings after Registration, e.g.
```
$GLOBALS['TCA']['tt_content']['types']['<my-CType>']['showitem'] = str_replace(
    'header;',
    '--palette--;;headers;',
    $GLOBALS['TCA']['tt_content']['types']['<my-CType>']['showitem']
);
```

**Comment by clivebeckett** [comment]
> Hi @clivebeckett you can always override any TCA Settings after Registration, e.g.
> 
> ```
> $GLOBALS['TCA']['tt_content']['types']['<my-CType>']['showitem'] = str_replace(
>     'header;',
>     '--palette--;;headers;',
>     $GLOBALS['TCA']['tt_content']['types']['<my-CType>']['showitem']
> );
> ```

Wonderful, thanks a lot for this tip, @achimfritz!

Since I was wondering and in case others see this and ask themselves the same question: the mentioned code must be added to:
`your-sitepackage/Configuration/TCA/Overrides/tt_content.php`
and `<my-CType>` must be replaced with the CType name of the container element you configured in this very file.
