### ISSUE TITLE
Multidomain installations / best practice?

### ISSUE THREAD

**Issue by criwe** [b13/container#255]
Hi!
It would be great to add some information how to use container in a multidomaininstallation.

Best,
Christoph

**Comment by DenisMir** [comment]
What problem have you got with multi domain installations?

**Comment by criwe** [comment]
Not a direct problem. But I am but thinking about how best to set this up.
If containers are defined in a sitepackage, then they are visible for all pages (in a multidomain installation for all projects). 
Therefore, my thought was whether it would not be better to use a separate site package to define the basic containers and then in the domain-related Sitempackages then only the customized fluidtemplates to deposit. What is not yet 100% clear to me in this scenario is what information I need to store where.

Therefore the suggestion to integrate a best practice example in the documentation.

Maybe it´s just an configuration problem?!

**Comment by chesio** [comment]
Container elements are just like any other content elements. So ask yourself how would you approach the problem for "normal" content elements.

I would use Page TSconfig to hide content element types per site:
```
TCEFORM.tt_content.CType.removeItems = html,table,...
```

See: https://docs.typo3.org/m/typo3/reference-tsconfig/main/en-us/PageTsconfig/TceForm.html#removeitems

**Comment by criwe** [comment]
That was the missing clue!
Thanks a lot!

**Comment by davidsteeb** [comment]
I'm late, but anyway: Container works nicely with EXT:content_defender, so depending on the setup of your installation you can work with "allowed.CType" for your backend layout colPos configuration. This way you don't have to remove another container element (or any other custom element, for that matter) in all site packages when one adds a new element.
