### ISSUE TITLE
In page module hiding/unhiding container child triggers content_defender error

### ISSUE THREAD

**Issue by bfzgaier** [b13/container#263]
Setup:
TYPO3: 11.5.10
container: 1.6.1
content_defender: 3.2.2

To reproduce, you need the following configuration:
- a column with a disallowed content element (content_defender)
- a container with a column which specifically allows the disallowed element

Steps:
1) Create the container element in the column. 
2) Add the disallowed content element to the created container
3) In the page module, try to hide the content element located in the container
4) Hiding content element fails with the error ["The record "%s" couldn't be saved due to disallowed value(s)."](https://github.com/IchHabRecht/content_defender/blob/1843e0d0825b78413ef20e4f1b82bdbfed8c52b9/Classes/Hooks/DatamapDataHandlerHook.php#L64) 

The problem is in ColumnConfigurationManipulationHook, which should override the page column configuration with the one set in the container.
https://github.com/b13/container/blob/625ad7c08074ba8846954cc64061ce5bca1fb52e/Classes/ContentDefender/Hooks/ColumnConfigurationManipulationHook.php#L42-L47

The page column configuration is used, because the container id ($parent) is not found. 
The function for finding the container id looks for predefined GET parameters.

https://github.com/b13/container/blob/625ad7c08074ba8846954cc64061ce5bca1fb52e/Classes/ContentDefender/Hooks/ColumnConfigurationManipulationHook.php#L59-L80

The url to hide a content element does not contain any of them.
`https://typo3.local/typo3/record/commit?data[tt_content][38][hidden]=1&redirect=/typo3/module/web/layout?token=8f2c0808256ad1a51b8733086b02c56f79a4e9ad&id=11#element-tt_content-38`

But there is a `data`-parameter with the same structure as `edit`. 
Changing line 72 to use `data` if `edit` is missing fixed the issue and allows you to hide/unhide the content element as expected.

**Comment by achimfritz** [comment]
@bfzgaier mh, do you use the same colPos in the backend_layout and in the container? (i cannot reproduce with different colPos (i think no content_defender Restrictions are aplied, if colPos do not match?)

**Comment by bfzgaier** [comment]
@achimfritz now that you mention it. I do not use the same colPos, but something similar is happening. 
I have extended content_defender to use a default configuration if a column does not have one. 
This allows us to globally disable the usage of specific elements without adding them to each colPos configuration.

And of course, the element is disallowed globally. I should have thought about it. I am sorry for the inconvenience.

I would appreciate it if you would still make the change to ColumnConfigurationManipulationHook.php, as it is not a destructive one.

If you don't, it is not that big of a deal.

Thank you for your time.

**Comment by bfzgaier** [comment]
I will close this issue.
I replaced the ColumnConfigurationManipulationHook.php with a custom implementation.
