### ISSUE TITLE
PageLayout partials not respected for page preview

### ISSUE THREAD

**Issue by buepro** [b13/container#272]
Custom partials defined to render the content preview in the page module are not respected. The following is just used outside container elements:

```
module.tx_backend.view.partialRootPaths.100 = EXT:pizpalue/Resources/Private/Partials/Backend
```

It could be corrected by assigning the TS configuration when constructing the `ContainerConfiguration`. In addition to the partials as well the layout pathes could be considered.

**Comment by achimfritz** [comment]
see comment https://github.com/b13/container/pull/273
