### ISSUE TITLE
Exclude paths via TypoScript

### ISSUE THREAD

**Issue by sefoxx** [b13/container#276]
Hi.

Is it possible, to use the wonderful container-Extension without integrating it to a sitepackage?

f.e. I'm using an old installation, where i would use containers instead of gridelements without using a sitepackage.
I installed the extension via the extension manager and now I want to save all my future changes and container-templates from overriding by a core update.
So I need to change all paths to the important files via TypoScipt.
Is it possible to get all the lines for adding them to the Root Template?

Best regards
Sebi

**Comment by achimfritz** [comment]
Hi @sefoxx , this is not possible, you need at least one own Extension where you register your Container-Content Elements into the TCA, s. 

- https://github.com/b13/container-example/
- https://github.com/b13/container-example/blob/master/Configuration/TCA/Overrides/tt_content.php
