### ISSUE TITLE
Call to undefined method Doctrine\DBAL\Driver\Mysqli\MysqliStatement::fetchAssociative()

### ISSUE THREAD

**Issue by mbsued** [b13/container#282]
with typo3 version 10.4.31 and container 2.0.0 i get the following error in frontend:

(1/1) Error
Call to undefined method Doctrine\DBAL\Driver\Mysqli\MysqliStatement::fetchAssociative()

in /html/typo3/typo3conf/ext/container/Classes/Domain/Factory/Database.php line 95
                    $queryBuilder->createNamedParameter($uid, \PDO::PARAM_INT)
                )
            )
            ->execute()
            ->fetchAssociative();
        if ($record === false) {
            return null;
        }
        return $record;

**Comment by achimfritz** [comment]
non-composer mode, right? argh, seems they have doctrine/dbal 2.10 (but ~2.13.1 is required by container composer requirements)

**Comment by achimfritz** [comment]
we revert changes regarding doctrine fetch-methods.
