### ISSUE TITLE
Get parent CType

### ISSUE THREAD

**Issue by bavarianbytes** [b13/container#285]
Beside the UID (`tx_container_parent`) it would be nice to check which `CType` the parent container element has in a fluid template.
That would allow to render child elements differently depending on in which container element they are wrapped.

Or is there already a way to do it i don't see?

**Comment by achimfritz** [comment]
Hi @bavarianbytes, you can do this using an own DataProcessor like e.g. 

https://github.com/b13/container-example/blob/master/Classes/DataProcessing/MyModHeaderProcessor.php
https://github.com/b13/container-example/blob/master/Configuration/TypoScript/2cols.typoscript

to add additional properties. 

Or use colPos, to detect CType, this will be possible if each container element different colPos.

We want to keep EXT:container Code as small and simple as possible and will not implement this feature in the Extensions

**Comment by bavarianbytes** [comment]
Ok, thank you for the example!
Do you a have a last hint how to get the added processed data to the child elements instead of the current container element?

**Comment by achimfritz** [comment]
something like this in your DataProcessor should work (not best solution)
```
        $queryBuilder = GeneralUtility::makeInstance(\TYPO3\CMS\Core\Database\ConnectionPool::class)->getQueryBuilderForTable('tt_content');
        $record = $queryBuilder->select('*')
            ->from('tt_content')
            ->where(
                $queryBuilder->expr()->eq(
                    'uid',
                    $queryBuilder->createNamedParameter($cObj->data['uid'], \PDO::PARAM_INT)
                )
            )
            ->execute()
            ->fetchAssociative();
        if ($record !== false) {
            $processedData['data']['parentCType'] = $record['CType'];
        }
```
