### ISSUE TITLE
Update Problem

### ISSUE THREAD

**Issue by transdata** [b13/container#287]
Error: Too few arguments to function B13\Container\Listener\BootCompleted::__construct(),...........
TYPO3 11.5.14
no Composer
Bootstrap_package

**Comment by mbsued** [comment]
same here the Error happens only on mainpage:
too few arguments to function B13\Container\Backend\Grid\ContainerGridColumn::__construct(), 3 passed in /html/typo3/typo3_src-11.5.14/typo3/sysext/core/Classes/Utility/GeneralUtility.php on line 3208 and at least 4 expected

Typo3 Version 11.5.14
no composer

**Comment by chesio** [comment]
@transdata - it seems to be the same error as mentioned here: https://github.com/b13/container/issues/279#issuecomment-1212907147
@mbsued - it seems to be the same error as mentioned here: https://github.com/b13/container/issues/279#issuecomment-1216607777

In both cases I would recommend to clear all caches and dump autoload information - see the already existing issue #279.

**Comment by mbsued** [comment]
@chesio clearing cache and dump autoload does not help, error remains on mainpage, on subpages the error does not appear.

**Comment by chesio** [comment]
@mbsued Could you post full stack trace? As far as I understand the object being initialized with too few arguments, it should be initialized in BE context only (as the class name suggests). It's weird that you get the error on frontend, would be good to know what execution path leads to it.

**Comment by mbsued** [comment]
@chesio following error in backend on mainpage:
<html>
<body>


Core: Exception handler (WEB): Uncaught TYPO3 Exception: Too few arguments to function B13\Container\Backend\Grid\ContainerGridColumn::__construct(), 3 passed in /html/typo3/typo3_src-11.5.14/typo3/sysext/core/Classes/Utility/GeneralUtility.php on line 3208 and at least 4 expected \| ArgumentCountError thrown in file /html/typo3/typo3conf/ext/container/Classes/Backend/Grid/ContainerGridColumn.php in line 29. Requested URL: http://p609185.mittwaldserver.info/typo3/module/web/layout?token=--AnonymizedToken--&id=1
--



</body>
</html>

**Comment by asche76** [comment]
error still occours with container 2.0.2 (T3 11.5.15)

**Comment by mk3media** [comment]
I had the same issue (no composer). After reading #279 I cleared typo3temp and everything works again. Might be nice to get some info about this problem and the fix in the update info (upload comment) from the extension manager – would have saved quite some time.

**Comment by SirRuddy** [comment]
Got the same problem with Typo3 10.4.31 (no composer). The Error happens only on mainpage like [mbsued] reported.

**Comment by vmans** [comment]
Here it is with a stacktrace. Using latest 11LTS and latest container version.


(1/1) ArgumentCountError

Too few arguments to function B13\Container\Listener\BootCompleted::__construct(), 0 passed in /var/www/clients/client14/web58/typo3_src_active/typo3/sysext/core/Classes/Utility/GeneralUtility.php on line 3252 and exactly 1 expected
in /var/www/clients/client14/web58/web/typo3conf/ext/container/Classes/Listener/BootCompleted.php line 25

     * @var Registry
     */
    protected $tcaRegistry;

    public function __construct(Registry $tcaRegistry)
    {
        $this->tcaRegistry = $tcaRegistry;
    }

at B13\Container\Listener\BootCompleted->__construct()
in /var/www/clients/client14/web58/typo3_src_active/typo3/sysext/core/Classes/Utility/GeneralUtility.php line 3252

        if (isset(self::$singletonInstances[$finalClassName])) {
            return self::$singletonInstances[$finalClassName];
        }
        // Create new instance and call constructor with parameters
        return new $finalClassName(...$constructorArguments);
    }

    /**
     * Returns the class name for a new instance, taking into account

at TYPO3\CMS\Core\Utility\GeneralUtility::makeInstanceForDi()
in /var/www/clients/client14/web58/web/typo3temp/var/cache/code/di/DependencyInjectionContainer_97ffb2ccbcdf5509935f8e440a37ad7f68f84758.php line 4372

     * @return \B13\Container\Listener\BootCompleted
     */
    protected function getBootCompletedService()
    {
        return $this->services['B13\\Container\\Listener\\BootCompleted'] = \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstanceForDi(\B13\Container\Listener\BootCompleted::class);
    }

    /**
     * Gets the public 'B13\Container\Listener\PageTsConfig' shared autowired service.

at DependencyInjectionContainer_97ffb2ccbcdf5509935f8e440a37ad7f68f84758->getBootCompletedService()
in /var/www/clients/client14/web58/typo3_src_active/vendor/symfony/dependency-injection/Container.php line 239

        try {
            if (isset($this->fileMap[$id])) {
                return /* self::IGNORE_ON_UNINITIALIZED_REFERENCE */ 4 === $invalidBehavior ? null : $this->load($this->fileMap[$id]);
            } elseif (isset($this->methodMap[$id])) {
                return /* self::IGNORE_ON_UNINITIALIZED_REFERENCE */ 4 === $invalidBehavior ? null : $this->{$this->methodMap[$id]}();
            }
        } catch (\Exception $e) {
            unset($this->services[$id]);

at Symfony\Component\DependencyInjection\Container->make()
in /var/www/clients/client14/web58/typo3_src_active/vendor/symfony/dependency-injection/Container.php line 219

    public function get(string $id, int $invalidBehavior = /* self::EXCEPTION_ON_INVALID_REFERENCE */ 1)
    {
        return $this->services[$id]
            ?? $this->services[$id = $this->aliases[$id] ?? $id]
            ?? ('service_container' === $id ? $this : ($this->factories[$id] ?? [$this, 'make'])($id, $invalidBehavior));
    }

    /**
     * Creates a service.

at Symfony\Component\DependencyInjection\Container->get()
in /var/www/clients/client14/web58/typo3_src_active/typo3/sysext/core/Classes/EventDispatcher/ListenerProvider.php line 103

     * @throws \InvalidArgumentException
     */
    protected function getCallable(string $service, string $method = null): callable
    {
        $target = $this->container->get($service);
        if ($method !== null) {
            // Dispatch to configured method name instead of __invoke()
            $target = [ $target, $method ];
        }

at TYPO3\CMS\Core\EventDispatcher\ListenerProvider->getCallable()
in /var/www/clients/client14/web58/typo3_src_active/typo3/sysext/core/Classes/EventDispatcher/ListenerProvider.php line 89

        }
        foreach ($eventClasses as $className) {
            if (isset($this->listeners[$className])) {
                foreach ($this->listeners[$className] as $listener) {
                    yield $this->getCallable($listener['service'], $listener['method']);
                }
            }
        }
    }

at TYPO3\CMS\Core\EventDispatcher\ListenerProvider->getListenersForEvent()
in /var/www/clients/client14/web58/typo3_src_active/typo3/sysext/core/Classes/EventDispatcher/EventDispatcher.php line 50

        // If the event is already stopped, nothing to do here.
        if ($event instanceof StoppableEventInterface && $event->isPropagationStopped()) {
            return $event;
        }
        foreach ($this->listenerProvider->getListenersForEvent($event) as $listener) {
            $listener($event);
            if ($event instanceof StoppableEventInterface && $event->isPropagationStopped()) {
                break;
            }

at TYPO3\CMS\Core\EventDispatcher\EventDispatcher->dispatch()
in /var/www/.../typo3/sysext/adminpanel/Classes/Service/EventDispatcher.php line 41

     */
    public function dispatch(object $event)
    {
        $this->dispatchedEvents[] = $event;
        return parent::dispatch($event);
    }
}

at TYPO3\CMS\Adminpanel\Service\EventDispatcher->dispatch()
in /var/www/.../typo3/sysext/core/Classes/Core/Bootstrap.php line 170

        $bootState->done = true;
        static::loadBaseTca(true, $coreCache);
        static::checkEncryptionKey();
        $bootState->complete = true;
        $eventDispatcher->dispatch(new BootCompletedEvent($disableCaching));

        return $container;
    }

at TYPO3\CMS\Core\Core\Bootstrap::init()
in /var/www/.../typo3/index.php line 20

// Set up the application for the backend
call_user_func(static function () {
    $classLoader = require dirname(__DIR__).'/vendor/autoload.php';
    \TYPO3\CMS\Core\Core\SystemEnvironmentBuilder::run(1, \TYPO3\CMS\Core\Core\SystemEnvironmentBuilder::REQUESTTYPE_BE);
    \TYPO3\CMS\Core\Core\Bootstrap::init($classLoader)->get(\TYPO3\CMS\Backend\Http\Application::class)->run();
});

at {closure}()
in /var/www/.../typo3/index.php line 21

call_user_func(static function () {
    $classLoader = require dirname(__DIR__).'/vendor/autoload.php';
    \TYPO3\CMS\Core\Core\SystemEnvironmentBuilder::run(1, \TYPO3\CMS\Core\Core\SystemEnvironmentBuilder::REQUESTTYPE_BE);
    \TYPO3\CMS\Core\Core\Bootstrap::init($classLoader)->get(\TYPO3\CMS\Backend\Http\Application::class)->run();
});

**Comment by mk3media** [comment]
Just updated to 2.0.4 without any issues (Typo3 11.5.x, no composer).

**Comment by chesio** [comment]
@vmans This is how `DependencyInjectionContainer_...::getBootCompletedService()` method looks on one of my TYPO3 11.5 installations:

```php
    /**
     * Gets the public 'B13\Container\Listener\BootCompleted' shared autowired service.
     *
     * @return \B13\Container\Listener\BootCompleted
     */
    protected function getBootCompletedService()
    {
        return $this->services['B13\\Container\\Listener\\BootCompleted'] = \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstanceForDi(\B13\Container\Listener\BootCompleted::class, ($this->services['B13\\Container\\Tca\\Registry'] ?? ($this->services['B13\\Container\\Tca\\Registry'] = \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstanceForDi(\B13\Container\Tca\Registry::class))));
    }
```

Note that the entire class is auto-generated by the Symfony Dependency Injection Component when cache is flushed via `Maintenance` > `Flush Cache`. It's not enough to `Flush all caches` from administration bar at the top.

**Comment by achimfritz** [comment]
Hi (non-composer-) guys, anyone have still problems with DI (after flushing cache + dump autolaod + clear typo3temp?)? because this is not a general bug. Else i will close this issue?

**Comment by mbsued** [comment]
You can close.
