### ISSUE TITLE
"[TASK] remove TYPO3 v9 fix for foreign table" results in very slow opening of contentelements in edit-mode.

### ISSUE THREAD

**Issue by n4-chris** [b13/container#295]
TYPO3 11.5.15
PHP 8.1.9
MySQL 5.7.39 
container 2.0.2 

"[TASK] remove TYPO3 v9 fix for foreign table" (e32591e9e007c18ede5ddd00be30de4aab3c81cf) results in very slow opening of contentelements in edit-mode.

tt_content has about **13K records**: opening a random CE in Backend for editing needs about 60s... after reverting this task, it opens immediately.

Maybe: Without the `foreign_table_where` instruction, also `'foreign_table' => 'tt_content'` should be removed: this loads all 13K tt_content-records (here in my installation) in the select-item-array, before itemsProcFunc comes into play... ;-)

**Comment by achimfritz** [comment]
@n4-chris mh, i cannot reproduce
my CE inside container:
![image](https://user-images.githubusercontent.com/2152991/188804625-a3960943-3447-4a1a-83d8-c7573cf72ca9.png)
my CE outside container:
![image](https://user-images.githubusercontent.com/2152991/188804670-d775ce82-50fe-43a4-827f-440a7fd8e461.png)
my TCA Configuration in Configuration Module
![image](https://user-images.githubusercontent.com/2152991/188804750-a214656b-c290-4524-aa00-05f7be9372d6.png)

**Comment by n4-chris** [comment]
@achimfritz 

Yeah you're right: the CE works as expected, also here, but there's a performance issue if you have a big load of data in tt_content like me:

![grafik](https://user-images.githubusercontent.com/112948745/188823171-f5903918-4123-462e-887e-be35c9cbb5ec.png)

The "foreign_table" property is obsolet: **the item-array will be filled with records from the table defined here**. And this is done **before your itemsProcFunc-call**. In my case $parameters['items'] is filled with 9458 records, which needs about a minute to load if you try to edit a CE. 

![grafik](https://user-images.githubusercontent.com/112948745/188823257-bdd21aa8-43ef-4cec-ac32-9e45153d6a2a.png)

After that filling of the above array, the txContainerParent method overwrites the $parameters['items']-array entirely with your containerFactory->buildContainer data.

So, without the "foreign_table" property everything works fine and fast! :-)

**Comment by achimfritz** [comment]
hm, without this configuration Tests fails: https://github.com/b13/container/runs/8227424031?check_suite_focus=true

**Comment by n4-chris** [comment]
Strange... according to the documentation, it should be possible to use "itemsProcFunc" without "foreign_table" etc.:

https://docs.typo3.org/m/typo3/reference-tca/11.5/en-us/ColumnsConfig/CommonProperties/ItemsProcFunc.html#tca-property-itemsprocfunc
