### ISSUE TITLE
Translation not possible

### ISSUE THREAD

**Issue by signupmeyers** [b13/container#321]
While trying to translate a page the following error appears:

#1476107295 TYPO3\CMS\Core\Error\Exception
PHP Warning: Trying to access array offset on value of type null in […]/public/typo3conf/ext/container/Classes/Hooks/Datahandler/CommandMapBeforeStartHook.php line 189

- Typo3 version 11.5.17 in composer mode
- php 8.1.7
- Container version 2.1.0

It throws the error in translate- and in copy-mode.

**Comment by achimfritz** [comment]
Hi @signupmeyers can you please test master branch? i will make a bugfix-release if everything is fine for you

**Comment by signupmeyers** [comment]
Hi @achimfritz,
Thank you for your bugfix.
The described error is fixed, but I have the now the same error in another class.
It is
`PHP Warning: Trying to access array offset on value of type null in […]/public/typo3conf/ext/container/Classes/Hooks/Datahandler/DatamapPreProcessFieldArrayHook.php line 62
`
Should I open an new error report for this one?

**Comment by achimfritz** [comment]
i have reopen the issue

**Comment by achimfritz** [comment]
Hi @signupmeyers  would you test again? (the master-branch?) (sorry, but i cannot reproduce the bug, so i cannot test)

**Comment by signupmeyers** [comment]
Hey @achimfritz,
It's working with the master-branch.

Thank you very much!
