### ISSUE TITLE
Usage of Containers for News-Elements

### ISSUE THREAD

**Issue by EricVonBrumby** [b13/container#323]
Hi,

I am currently testing the Usage of your Extension,
and i would like to use the container to change the Layout of the individual Elements of a News-List.
However I have not fond any solution, either by trial and error, nor by googling the issue.

So I have come to ask if there is any possible solution or a known 'hack' to make do.

Thanks in advance :)

**Comment by achimfritz** [comment]
@EricVonBrumby  what exactly do you mean with "Layout of the individual Elements of a News-List"

**Comment by EricVonBrumby** [comment]
I have a sys-folder containing multiple blog-posts:
![image](https://user-images.githubusercontent.com/79306575/198285829-257453ee-e461-487e-9712-58df582f0823.png)

Currently they are being rendered using the vanilla Typo3 Layout Options, that you can choose in the Appearance tab:
![image](https://user-images.githubusercontent.com/79306575/198285584-ba1f21bb-c14e-45b9-83fc-a0289cccde5a.png)


But I would prefer to use the Flexibility of your containers to change the layout of those posts, instead of using the Typo3 Vanilla Templates.

I hope that helps

**Comment by achimfritz** [comment]
@EricVonBrumby , sorry, i'm a little confused, what you are showing are Backend Layouts, but container is a Content Element

**Comment by georgringer** [comment]
basic content elements within EXT:news do work but regarding using ext:container it is getting more tricky as the content elements are handled within irre elements only.
If you really need that, I suggest to use the extension news_content_elements (See https://docs.typo3.org/p/georgringer/news/main/en-us/Addons/NewsContentElements/Index.html) which supports EXT:container as well.

@achimfritz I suggest closing this issue

**Comment by AstCommodore** [comment]
> basic content elements within EXT:news do work but regarding using ext:container it is getting more tricky as the content elements are handled within irre elements only. If you really need that, I suggest to use the extension news_content_elements (See https://docs.typo3.org/p/georgringer/news/main/en-us/Addons/NewsContentElements/Index.html) which supports EXT:container as well.

Hello @georgringer, you don't trigger the problem that child elements of an container (e.g. a multicolumn element) couldn't get created/edited in a IRRE field or is your new extension covering this "EXT:container" issue?

**Comment by AstCommodore** [comment]
The penny drops! I assumed IRRE is still in use in your extension.

Thank you for the detail and your fast response!

**Comment by achimfritz** [comment]
issue can be closed?

**Comment by EricVonBrumby** [comment]
Yes. Sorry for not responding in a timely manner. There was a break in the project and others were in focus. The issue has since been resolved
