### ISSUE TITLE
Copy-pasting a page with multicolumn container only preserves first column child.

### ISSUE THREAD

**Issue by SruthiKumar333** [b13/container#326]
I am using EXT:container (v2.1.0) along with EXT:flux (v9.5.0). If I copy and paste a page that has a 2-column container, only the colPos of child in the first column is preserved and the colPos of the child in second column is lost. Thus, the second column child is shown as unused content on the page. If I uninstall flux then this issue is gone. So it seems to be a conflict with flux.
TYPO3 version is 10.4.31. 
I really appreciate any help you can provide.

![image](https://user-images.githubusercontent.com/53466587/198579044-865dd229-4a0a-4e1b-9ac1-964f3d277e7a.png)

**Comment by SruthiKumar333** [comment]
Any update here?

**Comment by achimfritz** [comment]
EXT:container gives no support when using in combination with EXT:flux
