### ISSUE TITLE
Drag and drop of a textmedia element between two container CE does not work

### ISSUE THREAD

**Issue by einpraegsam** [b13/container#327]
I cannot describe it better than:
- Opening the page backend module
- See a textmedia and after that two container elements (e.g. 50/50) with one children per column
- Drag textmedia and drop it one slot down (between both container elements)
- It seems that all works fine but
- When reloading the page module, the element is still on the top position

And I don't have this issue on my local environment. Also the ajax request is fine and returns a JSON with "hasErrors:false". 

Anyone else with this strange behaviour? This is an old page with gridelements before and maybe some other garbage in the database - maybe there are conflicting values that I don't see?

TYPO3 11.5.17, container 2.1.1

**Comment by einpraegsam** [comment]
No, we just switched from gridelements to container 2. I can see that there is a ContainerMigrateSorting Update script. Do you think that this could help? What does it do?

**Comment by achimfritz** [comment]
the script fixes sorting field of content elements (sorting field in page-context was wrong in container < 2.0), sorting can also be wrong from gridelements. (s. https://github.com/b13/container/releases/tag/2.0.0)

**Comment by einpraegsam** [comment]
Thx for you quick reply. To keep number of open issues as little as possible, I will close this issue now, because only one page is affected at the moment. In addition we also use content-defender what could also be a conflicting part.
