### ISSUE TITLE
Drag and drop broken in v2 for TYPO3 v10

### ISSUE THREAD

**Issue by mikestreety** [b13/container#332]
Hey,

I've just upgraded to version 2.x on my TYPO3 install (v10.4.32) and it fails when you try and drag and drop items into containers. This doesn't seem to happen on v11 sites.

I get the following error:

![image](https://user-images.githubusercontent.com/354085/202173630-775fff98-4fe9-4a59-8b72-1c987f4ed612.png)

I have pinned it down to [this commit](https://github.com/b13/container/commit/f9af78352704d666886ed64f6a0c479dcab4cf6f) - specifically the removal of this method from `Classes/Hooks/Datahandler/DatamapBeforeStartHook.php`

```php
    /**
     * @param array $datamap
     * @return array
     */
    protected function extractContainerIdFromColPosInDatamap(array $datamap): array
    {
        if (!empty($datamap['tt_content'])) {
            foreach ($datamap['tt_content'] as $id => &$data) {
                if (isset($data['colPos'])) {
                    $colPos = $data['colPos'];
                    if (MathUtility::canBeInterpretedAsInteger($colPos) === false) {
                        [$containerId, $newColPos] = GeneralUtility::intExplode('-', $colPos);
                        $data['colPos'] = $newColPos;
                        $data['tx_container_parent'] = $containerId;
                    } elseif (!isset($data['tx_container_parent'])) {
                        $data['tx_container_parent'] = 0;
                        $data['colPos'] = (int)$colPos;
                    }
                }
            }
        }
        return $datamap;
    }
```

adding the call to `processDatamap_beforeStart`

```php
 $dataHandler->datamap = $this->extractContainerIdFromColPosInDatamap($dataHandler->datamap);
```

I have added the above method to the latest version of container on my TYPO3 v10 install and it **works** as expected. I does, however, cause the drag and drop to **break** in TYPO3 v11.5.19

**Comment by achimfritz** [comment]
Hi @mikestreety  does this also happen when you cut and paste the element? Any other extension installed? like gridelement, flux, past_reference? (for last case see https://github.com/b13/container/issues/297)
Have you run the container upgrade-migrations (https://github.com/b13/container/releases/tag/2.0.0)?

**Comment by mikestreety** [comment]
Hey @achimfritz, thanks for getting back to me.

- It still happens if you cut and paste elements
- I didn't realise the migration needed running, thanks

Your links to the issues sent me on a rabbit hole (sorry I didn't spot #297 before) and it turns out it _was_ paste reference.

I have made a pull request with the changes: https://github.com/Kephson/paste_reference/pull/10

**Comment by mikestreety** [comment]
As an update, a new version of paste reference (1.0.3) has been released to address and resolve this issue in TYPO3 v10

https://github.com/Kephson/paste_reference/commit/2c8dfea5f14e574abf14173047a853d1f21155b8
