### ISSUE TITLE
Container with content-defender maxitems=1

### ISSUE THREAD

**Issue by tukislife** [b13/container#334]
Hey,
I have a problem when trying to set maxitems to 1 in cols.

```
\TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance(\B13\Container\Tca\Registry::class)->configureContainer(
    (
        new \B13\Container\Tca\ContainerConfiguration(
            'textcolumnsgrid',
            'LLL:EXT:foo/Resources/Private/Language/locallang_be.xlf:wizard.textcolumnsgrid.title',
            'LLL:EXT:foo/Resources/Private/Language/locallang_be.xlf:wizard.textcolumnsgrid.description',
            [
                [
                    ['name' => 'Col-1', 'colPos' => 201, 'allowed' => ['CType' => 'text'], 'maxitems' => '1'],
                    ['name' => 'Col-2', 'colPos' => 202, 'allowed' => ['CType' => 'text'], 'maxitems' => '1'],
                    ['name' => 'Col-3', 'colPos' => 203, 'allowed' => ['CType' => 'text'], 'maxitems' => '1']
                ]
            ]
        )
    )
    ->setIcon('EXT:foo/Resources/Public/Icons/Backend/grid-col-3.svg')
    ->setBackendTemplate('EXT:foo/Resources/Private/Templates/Backend/Grid.html')
    ->setSaveAndCloseInNewContentElementWizard(true)
    ->setRegisterInNewContentElementWizard(false)
);
```
Settings "'maxitems' => '1'" does only work when the col is already filled.
![Bildschirmfoto 2022-12-05 um 13 24 31](https://user-images.githubusercontent.com/29711032/205637019-52d01213-2b98-48ab-9077-0bb6dcf50c42.png)

But when I try to fill the remaining 2 cols I get this Error in the saving process:
![Bildschirmfoto 2022-12-05 um 13 25 04](https://user-images.githubusercontent.com/29711032/205637144-26d02b70-4492-441b-afe1-749fd1c94d7b.png)

Setting the maxitems to a ridiculous high number fixes the saving process, but then the desired maxitems=1 is not possible.
It seems like the counting is not working as intended.

I also think this is a container issue, because I have no problems using content-defender for contentelements besides container.

TYPO3: 11.5.19
b13/container: 2.1.1
content-defender: 3.2.3

**Comment by chesio** [comment]
Hi @tukislife,

have you seen https://github.com/IchHabRecht/content_defender/issues/105? Perhaps it's the same problem you are having?

**Comment by tukislife** [comment]
Hey @chesio,
Thanks for the reply - I will look into it!
On first glance it seems like the same problem.
