### ISSUE TITLE
PHP8.1 - Undefined array key "tx_container_parent"

### ISSUE THREAD

**Issue by benjaminkott** [b13/container#336]
PHP Warning: Undefined array key "tx_container_parent" in /var/www/html/public/typo3conf/ext/container/Classes/Hooks/Datahandler/DatamapPreProcessFieldArrayHook.php line 62

**Comment by achimfritz** [comment]
@benjaminkott  when does this occure?

**Comment by georgringer** [comment]
I got this issue if extension is installed but DB compare is not done and therefore the column is still missing

**Comment by achimfritz** [comment]
in this case i think you should better Update your DB-Schema
