### ISSUE TITLE
Drag & Drop into the Container-Element not working

### ISSUE THREAD

**Issue by Oliver-KDS** [b13/container#339]

**Comment by achimfritz** [comment]
colPos is cast to integer by JS (https://review.typo3.org/c/Packages/TYPO3.CMS/+/75887 ) but EXT:container expects "<container-parent>-<colPos>" (still not sure how to fix this, maybe use an integer as delimiter instead of the "-")

**Comment by achimfritz** [comment]
fixed in master branch 
https://github.com/b13/container/pull/353
https://github.com/b13/container/commit/bf38dc3d4531132c895a563dbc4243cf4b54bbb8
