### ISSUE TITLE
Give more hints if misconfiguration happens

### ISSUE THREAD

**Issue by georgringer** [b13/container#342]
When migrating projects from gridelements, one task is to recreate all configurations which is most of the time a copy & paste job. however I stumbled upon issues which where completely my fault but the extension could have given me some hints about it:

- duplicate ctype: if copying configurations and forgetting to change the ctype I just realized it by seeing in the content element wizard that a configuration is missing.
- duplicate colpos: having the same colpos in one configuration is not a good thing but happens quite easily.

throwing exceptions if those issues happens would make the life of integrators easier

**Comment by achimfritz** [comment]
"duplicate ctype" may even be useful to override an existing container configuration
