### ISSUE TITLE
Error when adding a flex type field to a container

### ISSUE THREAD

**Issue by phillued** [b13/container#343]
Im getting this error if im trying to add a flex field:
" RuntimeException: Data structure identifier must be set, typically by executing TcaFlexPrepare data provider before"

I tried using the default pi_flexform field and a custom flex field (avhelpers_flex_field; the commented out lines) but its not working. The structure of the flex file is not broken. Im using this simple xml for testing:
```
<T3DataStructure>
  <ROOT>
     <type>array</type>
     <el>
        <xmlTitle>
           <TCEforms>
              <label>The Title:</label>
              <config>
                 <type>input</type>
              </config>
           </TCEforms>
        </xmlTitle>
     </el>
  </ROOT>
</T3DataStructure>
```
How i register the containers and add the flex field conf
```
$containerFlex = [];
foreach($container as $item) {
  GeneralUtility::makeInstance(ContainerRegistry::class)->configureContainer(
    (
    new ContainerConfiguration(
      $item['CType'],
      $item['title'],
      $item['description'],
      $item['conf']
    )
    )
      // set an optional icon configuration
      ->setIcon(ExtUtility::ICONS['container'] . 'container.svg')
  );

  if($flex = $item['flex']){
    $containerFlex[] = $item['CType'];

    // add Flexform to CType
    ExtensionManagementUtility::addPiFlexFormValue(
      '*',
      $flex,
      $item['CType']
    );
    //$GLOBALS['TCA'][$tableName]['columns']['avhelpers_flex_field']['config']['ds'][$item['CType']] = $flex;
  }
}

// Add flex field to "showitem" of CTypes
if(!empty($containerFlex)){
  ExtensionManagementUtility::addToAllTCAtypes(
    $tableName,
    'pi_flexform;Container Settings',
    implode(',', $containerFlex),
    'after:header'
  );

  //ExtensionManagementUtility::addToAllTCAtypes(
  //  $tableName,
  //  'avhelpers_flex_field',
  //  implode(',', $containerFlex),
  //  'after:header'
  //);
```

Im using TYPO3 11.5.21 and the error occurs in /sysext/backend/Classes/Form/FormDataProvider/TcaFlexProcess.php line 57.
I tried to debug it myself but i did not find out why the "dataStructureIdentifier" value is null for this container.

**Comment by stigfaerch** [comment]
@phillued how come you closed the issue?
Did you find a solution? What was it?

**Comment by phillued** [comment]
@stigfaerch oh i beleave it was that stupid error where i forgot the "FILE:" in my tsconfig for that container

For example it was
`flex = EXT:extension/Configuration/FlexForms/container/Layout/Container.xml`
insead of
`flex = FILE:EXT:extension/Configuration/FlexForms/container/Layout/Container.xml`
