### ISSUE TITLE
Using sorting/moving buttons in List-View on Container elements corrupts the related database entry

### ISSUE THREAD

**Issue by johollmann** [b13/container#347]
Tested on TYPO3 v 11.5.21 and Container v2.1.2 

Steps to reproduce:
1. create a blank page
2. create a container element on that page
3. create any other content element inside that container
4. go to list-view and click on the "Move down in list" button of the container element 
 
As a result the tt_content entry for that container get its own uid assigned to the field tx_container_parent and the field colPos is getting set to the configured first column for that container.
While you can still see all the elements in the list-view in page-view they disapear because of that miss behaivour.

Expected behaviour: tx_container_parent and colPos of the container element should not be modified

**Comment by achimfritz** [comment]
first at all: EXT:container is not working in List-Module, but only in Page-Module.
but i agree, your described scenario leeds to inconsistent datas (and Page-Module cannot be loaded after this operation (endless loop), so i will prevent this moving operation (background: you try to move the container inside himself (by moving him after his child), this should not be possible.
