### ISSUE TITLE
Copying and Paste after doesnt work correctly

### ISSUE THREAD

**Issue by togeissler** [b13/container#357]
If copying a container with child ces and then "paste after" another ce the copied container is empty and placed in an not allowed colPos...
![Unbenannt-1](https://user-images.githubusercontent.com/122776118/216268402-508bba1d-2a84-4d9d-a564-906dbda0d9e9.jpg)
![unbenutzt1](https://user-images.githubusercontent.com/122776118/216268759-0b07896a-f652-4a3f-aa08-b2e4b7bb71e5.png)
![unbenutzt2](https://user-images.githubusercontent.com/122776118/216269104-fcdba3f1-ff89-4109-8975-aab822a20b0c.png)
![unbenutzt3](https://user-images.githubusercontent.com/122776118/216269115-5945484f-fad6-48e2-9a8d-1c7addb44e2f.png)

TYPO3 Version --> 11.5.19 
container --> 2.1.2

**Comment by achimfritz** [comment]
Hi @togeissler  any other extensions installed, like gridelements, flux or paste_reference (some of them conflicts in different ways), or maybe any datahandler hooks or TCA-Configuration regarding colPos column?

**Comment by togeissler** [comment]
Hi,
these extensions are installed:
ke_search --> 4.5.1
yoast_seo --> 8.3.1
staticfilecache --> 12.4.5
mask --> 8.0.5
fontawesome_provider --> 1.0.0
dp_cookieconsent --> 11.6.3
container --> 2.1.2
+ our sitepackage

So i don't think they might be the reason...

Following our container-TYPOSCRIPT

```
tt_content.3col-container =< lib.contentElement
tt_content.3col-container {
  templateName = 3col-container
  dataProcessing.13 = B13\Container\DataProcessing\ContainerProcessor
}

lib.contentElement = FLUIDTEMPLATE 
lib.contentElement {
   format = html
   templateRootPaths.1 = EXT:agentur_ledermann_dummy_template/Resources/Private/Extensions/Container/Templates/
   partialRootPaths.1 = EXT:agentur_ledermann_dummy_template/Resources/Private/Extensions/Container/Partials/
   layoutRootPaths.1 = EXT:agentur_ledermann_dummy_template/Resources/Private/Extensions/Container/Layouts/
   variables {
     # Verknüpfung der Inhalte mit dem Backend Layout 
     # content_1 < styles.content.get
   }
 }
```

It is working if we use the button to paste the copied container instead of using the context menu of the ce:
![copypaste ](https://user-images.githubusercontent.com/122776118/216299534-eea89029-2b0d-4184-a6ee-ebbf8ad6bd2b.png)

![copypaste2 ](https://user-images.githubusercontent.com/122776118/216299745-3b90c2b1-dc72-4830-8326-60a4b20ff23f.png)

**Comment by achimfritz** [comment]
ok, i see, wanna go to fix this issue

**Comment by t3touch** [comment]
Hello, 

I got same problem in TYPO3 12.1.3 on drag n drop CE's into a container. 

<img width="626" alt="grafik" src="https://user-images.githubusercontent.com/1329120/216443215-7c693051-2c34-4d71-8f48-baea13d41eae.png">

<img width="458" alt="grafik" src="https://user-images.githubusercontent.com/1329120/216443364-4f3a28df-c5c7-46a7-9a85-4c541bf80954.png">
