### ISSUE TITLE
Warning when logging into TYPO3 v12.2

### ISSUE THREAD

**Issue by chrcan** [b13/container#363]
After updating from v12.1 to v12.2 I get a warning in the FE like login to the TYPO3 backend.
container versions : * 2.1.2 is installed. 

(1/1) #1476107295 TYPO3\CMS\Core\Error\Exception
PHP Warning: Undefined array key "global" in /var/www/html/vendor/b13/container/Classes/Listener/PageTsConfig.php line 36

**Comment by achimfritz** [comment]
s. https://github.com/b13/container/tree/bugfix/ts-config

**Comment by achimfritz** [comment]
fixed in 2.2.0
