### ISSUE TITLE
Display Current Container Label in Page Module

### ISSUE THREAD

**Issue by linawolf** [b13/container#368]
When you have several similar containers with the same column names they can only be differentiated by Icon by the editors. Is it possible to display the current containers label similar to how it was done in Gridelments?

Container:

![image](https://user-images.githubusercontent.com/48202465/220552814-1aacbced-5c5e-4b7b-884e-ea07d07fbea0.png)

Gridelements:

![image](https://user-images.githubusercontent.com/48202465/220552728-fafb3168-1e9f-4eb9-b9b5-629e39c2bc3f.png)

**Comment by achimfritz** [comment]
Hi @linawolf just use your own Backend-Container-Grid for rendering. This can be set during container Registration by calling `setGridTemplate(EXT:<my-site-package>/Resources/Private/BackendPreview/ContainerGrid.html)` (s. https://github.com/b13/container#methods-of-the-containerconfiguration-object, https://github.com/b13/container/blob/master/Resources/Private/Templates/Grid.html)
`containerRecord` is assign to template, so you can use `containerRecord.CType`
```
<f:if condition="{containerGrid}">
    <h4>{containerRecord.CType}</h4>
    <f:render partial="PageLayout/Grid" arguments="{grid: containerGrid, hideRestrictedColumns: hideRestrictedColumns, newContentTitle: newContentTitle, newContentTitleShort: newContentTitleShort, allowEditContent: allowEditContent}" />
</f:if>
```
or translate it with corrospending label of CType
