### ISSUE TITLE
PHP Warning: Undefined array key "global" 

### ISSUE THREAD

**Issue by bihor** [b13/container#373]
container 2.1.2 is not fully compatible with PHP 8.1 and TYPO3 12.2
In the debug mode I get this error message:

(1/1) #1476107295 TYPO3\CMS\Core\Error\Exception

PHP Warning: Undefined array key "global" in C:\xampp\htdocs\git\typo312ohne\typo3conf\ext\container\Classes\Listener\PageTsConfig.php line 36

**Comment by achimfritz** [comment]
Hi @bihor should be already fixed in 2.2.0
