### ISSUE TITLE
Unused elements warning with database that returns string for uid

### ISSUE THREAD

**Issue by guppy42** [b13/container#374]
Continuing from #308 

You get backend warnings about unused elements when ever you put anything into a container - I tracked the reason down to

EXT:container/Classes/Domain/Model/Container.php@L143 it needs to be
            if ((int)$childRecord['uid'] === $childUid) {
            
Since the ChildRecord could be (mysql version, sqlite, etc) loaded with 'uid' as strings.

Test against git as of this posting

**Comment by maryahcm** [comment]
Hello,

I had the same problem, when translating a container.

I tracked that down to the function  B13\Container\Hooks::addContainerChildren() (telling whether the item is used or not), which in turn calls B13\Container\Domain\Model::hasChildInColPos(), as mentioned above.

The idea is to make sure if actually the translated elements of a container will have the value of tx_container_parent which is equal to their direct parent or to the parent in the original language. It is also necessary to review the behavior of the function responsible for making the copy/translation.

Thank you.
