### ISSUE TITLE
Sorting problem in 2.1.2

### ISSUE THREAD

**Issue by firmenpunkt** [b13/container#379]
I don't know, if it relates to previous issues, but there is a problem with keeping the sorting place if there is a container element and an element outside a container after it. The non-container element (e.g a Mask element between 2 Containers) jumps to the first position in the page, in Page module. Probably because it does not get a proper sorting number. TYPO3 11.5.25
It works in 2.1.1

**Comment by achimfritz** [comment]
Hi @firmenpunkt 
works with 2.1.1 but not with 2.1.2? i do not see any change that can be responsible for this bug. (have you tried current Version of EXT:container? (2.2.1))

can you give more information, when exactly do the non-container element jumps to the first position in the page?, do you move it? or edit it?, maybe some screenshot can help me, to understand the problem?

**Comment by achimfritz** [comment]
Hi @firmenpunkt any news? else i will close this issue?

**Comment by firmenpunkt** [comment]
I am closing this issue, and when I can reproduce it in a concrete case, I will reopen it or make a new ticket.

**Comment by achimfritz** [comment]
Hi @firmenpunkt have a look to the commands in EXT:container, some of them can help you, if migrated from gridelements
