### ISSUE TITLE
Error after deinstall of old version 1.0 an install new version in typo3 11.5.25

### ISSUE THREAD

**Issue by joachim-lechner** [b13/container#385]
error ist thrown:

(1/1) Error

Class "B13\Container\Updates\ContainerMigrateSorting" not found

typo3conf/ext/container/ext_localconf.php line 90

        $datamapHooks,
        $GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['t3lib/class.t3lib_tcemain.php']['processDatamapClass']
    );

    $GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['ext/install']['update'][B13\Container\Updates\ContainerMigrateSorting::IDENTIFIER]
        = B13\Container\Updates\ContainerMigrateSorting::class;
    $GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['ext/install']['update'][B13\Container\Updates\ContainerDeleteChildrenWithWrongPid::IDENTIFIER]
        = B13\Container\Updates\ContainerDeleteChildrenWithWrongPid::class;
});

typo3conf/ext/container/ext_localconf.php line 94.

**Comment by achimfritz** [comment]
Hi @joachim-lechner , please flush all caches and dump autoload in Install Tool (for non-composer-mode) (and/or clear typo3temp) (s. also https://github.com/b13/container/issues/287 and https://github.com/b13/container/issues/279

**Comment by joachim-lechner** [comment]
Perfect, thankyou, now its working again.
