### ISSUE TITLE
Multiple container from mutiple themes show up multiple times in type select

### ISSUE THREAD

**Issue by markussoeth** [b13/container#386]
I have a TYPO3 instance with multiple domains and multipe themes.
Every theme uses container.

A user wants to change a content element with the drop-down menu.
In the type select every container from every theme shows up.

Example
![grafik](https://user-images.githubusercontent.com/306641/229156609-0e69b519-9c01-4679-b0be-4da4171d92a8.png)

Here you see "Störer mit Bild" or "Counter" appears multiple times, even if it should not possible to use it in this domain.

This only happens here.
Not in the content wizard or anywhere else.

**Comment by SvenJuergens** [comment]
@markussoeth hi, have you found a workaround in the meantime?

**Comment by achimfritz** [comment]
Hi @markussoeth , what is a theme? do you mean same as described here: https://github.com/b13/container/issues/404 (if so you please use suggested solution)

**Comment by markussoeth** [comment]
> Hi @markussoeth , what is a theme? do you mean same as described here: #404 (if so you please use suggested solution)

Thank you for the hint. 
It is so. 
Oh.. and a theme is whats mostly called a sitepackage in TYPO3. Sometimes I fall back into Wordpress language :-)
