### ISSUE TITLE
Issues with workspaces?!

### ISSUE THREAD

**Issue by georgringer** [b13/container#387]
this is just a a copy&paste of the issue reported at https://forge.typo3.org/issues/100504 by @bihor

> When I use the container-extension
https://extensions.typo3.org/extension/container
and create a container-element and then add some normal elements to it, everything is OK.
But when I am in a Workspaces-mode and then delete this container, only the container-element will be deleted.
The childs of the containter will not be deleted when I am in the workspaces-mode.
When I am in the live-workspace, every child of a container will be deleted too.
In the workspace-mode, the childs of a deleted container will be shown at the bottom of the page under the "Unused" column.
Because this happens only in the workspace-mode, this must be a bug in the workspaces-extension.

**Comment by achimfritz** [comment]
i cannot reproduce, i have
![live](https://user-images.githubusercontent.com/2152991/232235379-07a17715-398b-4206-a538-5032e8c2c56f.png)
 one container and one child in live workspace, DB looks:
```
mysql> select uid,CType,header,t3ver_oid,t3ver_wsid,t3ver_state from tt_content;
+-----+---------------------------------+-----------+-----------+------------+-------------+
| uid | CType                           | header    | t3ver_oid | t3ver_wsid | t3ver_state |
+-----+---------------------------------+-----------+-----------+------------+-------------+
|   1 | b13-2cols-with-header-container | container |         0 |          0 |           0 |
|   2 | header                          | child     |         0 |          0 |           0 |
+-----+---------------------------------+-----------+-----------+------------+-------------+
```
i switch to Workspace and deleted container, child is also deleted:
```
mysql> select uid,CType,header,t3ver_oid,t3ver_wsid,t3ver_state from tt_content;
+-----+---------------------------------+-----------+-----------+------------+-------------+
| uid | CType                           | header    | t3ver_oid | t3ver_wsid | t3ver_state |
+-----+---------------------------------+-----------+-----------+------------+-------------+
|   1 | b13-2cols-with-header-container | container |         0 |          0 |           0 |
|   2 | header                          | child     |         0 |          0 |           0 |
|   3 | header                          | child     |         2 |          1 |           2 |
|   4 | b13-2cols-with-header-container | container |         1 |          1 |           2 |
+-----+---------------------------------+-----------+-----------+------------+-------------+
```
i do not see child as unused element
![ws](https://user-images.githubusercontent.com/2152991/232235496-0d1910d5-1e8c-4b7c-b000-3e4b4f52bc58.png)

can you give more hints? (TYPO3 Version etc.)

**Comment by bihor** [comment]
You are right. In normal cases this does not happen.
I could reproduce it only in workspace mode AND when I copy a container from another page.
After deleting the copied container, the elements of the container are not deleted.
With TYPO3 10 I could not reproduce it too.
But with TYPO3 11 I could reproduce it in 2 different projects.

**Comment by zenoussi** [comment]
Another problem is that deleted images (within a container) are included again in the newly inserted container element after copy/paste. Can you confirm this as well? LD

**Comment by bihor** [comment]
Yes, I can confirm that a deleted image is the when I copy the container in the workspace mode.
