### ISSUE TITLE
no drag'n'drop apply

### ISSUE THREAD

**Issue by p-view** [b13/container#399]
Is not possible to drag'n'drop or paste after containers. The position has no Change.
What can i do? 
The Problem ist in different Projects and Version. current Typo3 11.5.31 Container [2.2.1]

**Comment by achimfritz** [comment]
Hi @p-view did you upgrade from container 1.x?, did you run `vendor/bin/typo3cms container:sorting` ?
can you give a simple tt_content table dump (with min. CEs) where i can reproduce this behaviour? (because it should be work in general)

**Comment by p-view** [comment]
was a fresh instalation without composer. container:sorting gives me a hint for another pid. I think thats ot the problem. is it possible to write you a email? than i can give you a backend login.

**Comment by birgitberlin** [comment]
same problem here - but only with EXT:mask CEs
TYPO3 11.5.27
EXT:container 2.2.2

I have different containers with only 1 colPos (201).
It is not possible to drag and drop mask CEs (teasers) inside.

May be ist an problem with sorting in EXT:mask.

Works with FSC CEs.

**Comment by birgitberlin** [comment]
Works now with EXT:mask 8.1.5

**Comment by achimfritz** [comment]
any opened points here (that are reproducible with a TYPO3/container Vanilla Instance)
