### ISSUE TITLE
Using the same colPos with different names not possible

### ISSUE THREAD

**Issue by davidsteeb** [b13/container#4]
I want to use two container elements: A two column container and a three column container.
Using containers with colPos values 201 and 202 for the two column container, and 201, 202, and 203 for the three columns containers seems to make the most sense since editors can use the containers and switch between the different configurations without having to rearrange all content elements already saved into one of the first two columns.

If I set names like 201 => left, 202 => right for the two column container, and 201 => left, 202 => middle, 203 => right for the three column container one of the following is happening:
Either the two column element has column names in the backend of "left" and "middle" (instead of "left" and "right"), or the three column element has column names of "left", "right" and "right".

I can fix this by applying pageTSconfig or using columnsOverride configuration (not tested) but it would make more sense to have that solved on registering a container cType.

**Comment by Hobokens** [comment]
I would like to support @davidsteeb's proposal. I'm using container with bootstrap templates. I have several two column containers with different columns widths. So it is important to show by name what the actual width of a column is.

**Comment by davidsteeb** [comment]
tested, fixed.
