### ISSUE TITLE
Container registry for multidomain setup

### ISSUE THREAD

**Issue by phillued** [b13/container#404]
Is there a way to register different containers for specific pages (siteroots) only? 
Like default content elements where its possible to include the tsconfig backend wizard only for specific pages.

The only possible solution i found is to explicetly allow/disallow every single element in backend layouts and container configs. But that can be a bit annoying whit a large amount of elements/sites.

**Comment by achimfritz** [comment]
@phillued you are right, container-registry is "global" (knows nothing about any PageTree or Page ID), and you are right with your suggested solution.
