### ISSUE TITLE
Container can be drag and drop into itself

### ISSUE THREAD

**Issue by DennisPrsvc** [b13/container#405]
## Issue
I found an issue in the new TYPO3 v12 where you can drag a container into itself. After that you can only edit the container via list.

## Solution
With css you can disable the drop fields inside a clone, so it is no longer possible to drop a container into itself.

**Comment by achimfritz** [comment]
@DennisPrsvc , hm, how do you do this? if i drag a container element the whole container (with all child-elements) is moved, and i cannot drop it into itself? Furthermore there is a check in the datahandler hook which prevent moving/copy container into itselfs, s. https://github.com/b13/container/blob/master/Classes/Hooks/Datahandler/CommandMapBeforeStartHook.php#L70
(i see now, that this not work for nested container, i will fix this (this can happen by move/copy container by clipboard, or in list-module)
