### ISSUE TITLE
PHP Warning: Undefined array key "global" in /html/typo3/typo3conf/ext/container/Classes/Listener/PageTsConfig.php line 36

### ISSUE THREAD

**Issue by Fasna-kv** [b13/container#407]
Im getting error when i install the latest version of typo3 container for my typo3 12.4 
Im not able to access my typo3 backend

PHP Warning: Undefined array key "global" in /html/typo3/typo3conf/ext/container/Classes/Listener/PageTsConfig.php line 36

**Comment by S3b0** [comment]
This is because TER version does not match current composer version, wherein this is already fixed.

**Comment by achimfritz** [comment]
@Fasna-kv  2.2.2 is on TER
