### ISSUE TITLE
Migration of gridelements features

### ISSUE THREAD

**Issue by phillued** [b13/container#409]
Are there any plans to migrate some of the nice Backend-Features the gridelements Extension provided?

Like these:
- The "copy from another page" Button
- The "insert as reference"option
- The preview for shortcuts

**Comment by bmack** [comment]
Hi @phillued ,

EXT:container just provides custom containers for other content elements. It was never intended as a replacement for gridelements and all its features. Gridelements also delivers even more features, such as limiting inserting types of content elements into a grid, which EXT:content_defender solves as well. Also gridelements ships with a drag+drop feature for new content elements in the page module and additional flexform settings to be provided per gridelements.

For the future maintenance of the container extension, we want to keep the feature set as minimal as possible to keep updates for future TYPO3 versions as easy as possible, and to have a maximum compatible with as many TYPO3 versions as possible.

For your use cases, there might be already extensions available that solve your wishes: https://extensions.typo3.org/extension/paste_reference - I guess there are even more of them.

**Comment by phillued** [comment]
Well, this extension just solves my wishes completely. How did i not find this🤦 Great thanks!
