### ISSUE TITLE
Upgrade wizard on TYPO3 v11.5

### ISSUE THREAD

**Issue by visualmovement** [b13/container#410]
Running the Upgrade wizard in Typo3 11.5.27 throws a TypeError:

`B13\Container\Tca\Registry::getAvailableColumns(): Argument #1 ($cType) must be of type string, int given, called in /.../public/typo3conf/ext/container/Classes/Integrity/Sorting.php on line 57`

thrown in file

`/.../public/typo3conf/ext/container/Classes/Tca/Registry.php in line 184`

In version 1.6.1 the problem does not exist. From 2.0.0 the error occurs. (Also tested with the latest 2.2.2)

**Comment by achimfritz** [comment]
Hi @visualmovement  do you use integer as CType? (should be a string, like database column?)

**Comment by visualmovement** [comment]
The error disappeared at some point. Didn't investigated any further back then. Just checked the sitepackage git changelog and you are right! Had a CType called '5050' but renamed it obviously. 

In retrospect, the error message now also makes perfectly sense :-)

**Comment by cweiske** [comment]
We also had a container with name "100" that brought this error.

We changed its name, and the typoscript was changed as follows:
```diff
-tt_content.100 =< lib.contentElement
-tt_content.100 {
-  templateName = 100
+tt_content.Full =< lib.contentElement
+tt_content.Full {
+  templateName = Full
   dataProcessing.13 = B13\Container\DataProcessing\ContainerProcessor
 }
```
