### ISSUE TITLE
Custom backend templates/partials not supported at the moment

### ISSUE THREAD

**Issue by j-schmidt-magenta-mannheim** [b13/container#412]
Hello. We use custom backend templates to display more information. The official way to do this in TYPO3 v12 is to create the file `Configuration/page.tsconfig` and therein write `templates.typo3/cms-backend.5555 = my-vendor/my-extension:Path/To/My/TemplatesEtc`.

This works outside containers, but not inside, unless we add our own path to `$this->gridPartialPaths` inside `Classes/Tca/ContainerConfiguration.php` which of course we would like to avoid.

Since the container configuration is created during the autoload configuration creation the page TS solution would require changes to how and when EXT:container creates its configuration. An extension setting on the other hand would not suffer from that problem, but the configuration could then not depend on the page id – which probably would be a problem to very few people, to us it would not.

What are your thoughts and plans on this?

**Comment by achimfritz** [comment]
Hi @j-schmidt-magenta-mannheim , you are right, the configuration is completley static (and cached) and cannot be changed at runtime.
there are no plans to change this behaviour, configuration is indepented of page id, and so independent page TS, "nothing" can be changed at runtime (not only the BE-Template, but also the grid-configuration or any labels)
you need to configure an other container-element, if you need an other BE-Preview.
