### ISSUE TITLE
Sorting of content and container elements in T3 V12 LTS does not work correctly

### ISSUE THREAD

**Issue by Kosmonaut2** [b13/container#415]
If you have created various content elements in the backend and these are also container elements, the sorting no longer works correctly if many elements (for example 20) are created here. Without container elements - only with Typo3's own elements such as headings, text/media, images etc. - the sorting works correctly, but if container elements are also created there, the sorting goes crazy at some point. New elements (e.g. headline) are not placed in the desired position - for example at position 17. Every time the element is inserted at the top of the page and you can't move it to the desired position with drag'n'drop. Manual sorting via the list function also blocks with a large number of created components. I only get the desired element moved to position 13. It does not go any further down. The next time I click on the "Arrow down" button, the element moves back up to position 12. Cutting and pasting at the desired position does not work either. Even creating a new content element at the desired position does not work.
It would be really great if you could take a look at this.

**Comment by achimfritz** [comment]
Hi @Kosmonaut2, did you update EXT:container from 1.x to 2.x? did you run the sorting migration command `container:sorting` ?

**Comment by vmans** [comment]
For me the Upgrade wizard

EXT:container: Migrate "container" sorting

Results in:

TypeError
TYPO3\CMS\Core\Authentication\AbstractUserAuthentication::start(): Argument #1 ($request) must be of type Psr\Http\Message\ServerRequestInterface, null given, called in /var/www/clients/client15/web76/web/vendor/typo3/cms-core/Classes/Core/Bootstrap.php on line 545

(PHP8.1.4; TYPO3 12.4.0 and .1)

**Comment by achimfritz** [comment]
the wizard not works (currently) on v12, you need to run the cli command `vendor/bin/typo3 container:sorting --apply` or run upgrade wizard on v10 or v11 (not running the migration leeds to the problems you described)

**Comment by Kosmonaut2** [comment]
whow, it works! the addition "--apply" was the crucial information to start the wizard. we had see the wizard fail but we did not know how we can fix it and we did not found anywhere an information about the solution. no matter - we are happy. thank you!

**Comment by Kosmonaut2** [comment]
I'm close the ticket.
