### ISSUE TITLE
Incorrect sorting values on nested containers lead to incorrect translations (sorting broken)

### ISSUE THREAD

**Issue by DenisMir** [b13/container#425]
TYPO3: 11.5.28
Container: 2.2.3

We recognized incorrect sorting values on translations in free mode. After some debugging we found out that weird/incorrect `sorting` values for the content elements (including containers) on `sys_language_uid  = 0` are the reason for this translation problems. This problem only exists for container 2.x! 

Here is an example on how to reproduce the error. The order in which you create the containers and elements is important!

- Create a container A
- Nest container B in container A
- Create child element CH1 in container B
- Create child element CH2 in container B (below CH1)
- Nest container C in container A (below container B)
- Create child element CH3 in container C

So we have the following picture in the backend: 

![Bildschirmfoto 2023-07-04 um 13 38 29](https://github.com/b13/container/assets/157281/ef7cc423-4755-473e-8072-1615af2fe267)
![Bildschirmfoto 2023-07-04 um 13 38 39](https://github.com/b13/container/assets/157281/1d3a31ed-28b8-488a-916d-708eb6201737)

This leads to the following picture in the `tt_content` table: 

![Bildschirmfoto 2023-07-04 um 13 37 21](https://github.com/b13/container/assets/157281/04580ba0-4fdd-4cd2-afcf-ae08851c9dd5)

When translating this one to a new language in free (copy) mode we get the following picture in the backend: 

![Bildschirmfoto 2023-07-04 um 13 40 35](https://github.com/b13/container/assets/157281/1ac8be8f-e9ec-4028-bbd4-d36626e4c04a)

What happens is that CH1 and CH2 got a broken ordering now. 

This leads to the following picture in the database: 

![Bildschirmfoto 2023-07-04 um 13 42 09](https://github.com/b13/container/assets/157281/365c54f6-bfdc-4ad7-bdcc-ab75a045e6b1)

You can prevent the error when creating the elements in the following order: 

- Create a container A
- Nest container B in container A
- Nest container C in container A (below container B)
- Create child element CH1 in container B
- Create child element CH2 in container B (below CH1)
- Create child element CH3 in container C

This leads to the `tt_content` table be like: 

![Bildschirmfoto 2023-07-04 um 14 17 49](https://github.com/b13/container/assets/157281/0e80983f-dc8f-4f3e-b3e7-a9a8f808eb39)

When you translated this one in free (copy) mode it will be correct.

**Comment by achimfritz** [comment]
bug can be break down to:

Create a container A
Nest container B in container A
Create child element CH1 in container B
Create child element CH2 in container A (below container B)

this leads to:
```
MariaDB [db]> select uid,colPos,tx_container_parent,sorting,header from tt_content order by sorting;
+-----+--------+---------------------+---------+--------+
| uid | colPos | tx_container_parent | sorting | header |
+-----+--------+---------------------+---------+--------+
|   1 |      0 |                   0 |     256 | A      |
|   2 |    200 |                   1 |     512 | B      |
|   8 |    200 |                   1 |     640 | CH2    |
|   3 |     25 |                   2 |     768 | CH1    |
+-----+--------+---------------------+---------+--------+
```
but CH2 should be after CH1 (sorting should be: A,B,CH1,CH2) (looks like CH2 is insert after B, instead of after CH2, looks like we need some rekursive calls in https://github.com/b13/container/blob/master/Classes/Domain/Service/ContainerService.php#L56) 

i will care, thanks for reporting

**Comment by DenisMir** [comment]
Thank you very much for fixing it @achimfritz. 👍
