### ISSUE TITLE
Drag & Drop v12

### ISSUE THREAD

**Issue by ttg-team-web** [b13/container#443]
we have an issue when drag & dropping Mask Elements between/into containers in the backend.

we have updated the extension to 2.3 and the bugfix about this issue ist applied but it persists https://github.com/b13/container/pull/353

the mask-element loses it's colpos and container parent on dropping it into a new position. at first everything looks correct in the backend view, but upon reload the element falls into the "unused" section and the colpos + parent look like this
![image](https://github.com/b13/container/assets/109278425/0ac6bfff-2745-429a-a150-143d2035b9bf)

some searching in the code, makes it seem as if the casting to integer of the string containing the coontainer-id + new delimiter + colpos is not working correctly

can you take a look at this issue again?

**Comment by achimfritz** [comment]
@ttg-team-web  can you please describe, how i can reproduce this issue on a Vanilla TYPO3 + container?

**Comment by ttg-team-web** [comment]
we are working with mask for out content elements but this behaviours has also been tested and replicated with native typo3 elements like "text":
- create a container
- create an element in the container
- in the backend view / page module drag and drop the element into another container or column
- reload the site / backend view
- element should now be in the unused section and when edited "colpos" and "tx_parent_grid" should be filled as above

**Comment by achimfritz** [comment]
@ttg-team-web , mh, this works for me, (and should work in general), there is also a Test-Case for this Scenario (https://github.com/b13/container/blob/master/Tests/Acceptance/Backend/LayoutCest.php#L160)

i see a very large integer value of colPos in your screenshot, maybe there is a problem with the delimiter in V12
https://github.com/b13/container/blob/master/Classes/Backend/Grid/ContainerGridColumn.php#L23
can you give me your uids from all relateded DatabaseRecords (pages, tt_content), do you have very large uids? (max(uid) from tt_content/pages?), this could be an explanation of your described scenario (maybe i can increase the `CONTAINER_COL_POS_DELIMITER_V12` constant)

**Comment by ttg-team-web** [comment]
@achimfritz  i don't believe the uids themselves are the issue, like i said in my original message, i believe the casting of the string containing coontainer-id + new delimiter + colpos to integer is not working correctly. this is done here https://github.com/b13/container/blob/master/Classes/Backend/Grid/ContainerGridColumn.php#L46

nonetheless here are the uids involved in my test above:
- pages uid: 5 > max uid 38487
- container uid: 130881
- tt_content uid: 130882 > max uid 270740

so yes we have very high uids, but since @TonyMarc could replicate the problem on a vanilla installation...

**Comment by achimfritz** [comment]
@ttg-team-web , ok, thanks, your uids are all < 999990, so should be no problem.

what exactly do you meen, with "casting of the string containing coontainer-id + new delimiter + colpos to integer is not working correctly"? how can this not be correctly? (all 3 parts are integers, right?).

Please give me more hints, how this is reproduceable

**Comment by ttg-team-web** [comment]
@achimfritz all 3 parts should be integers yes, but in the getDataColPos() function all three parts are combined into one string and then cast to integer. this results in the string of numbers that you see above in my screenshot in the colpos field. so something is not correct here.

as a test i printed the combined container-id + new delimiter + colpos string and the result when you cast it to integer in the getDataColPos() function.
see here a few different strings that all return the same result when cast.

![image](https://github.com/b13/container/assets/109278425/d54eae33-20d6-4ef8-bf85-98b7fb17a03c)

does this help/make my point a bit clearer. this is about as far as i went into the container code before i made my issue here.

**Comment by ttg-team-web** [comment]
@achimfritz yes, our local environment is a 32bit system. checking `PHP_INT_MAX` confirmed it, it is indeed set to that value (2147483647)

**Comment by achimfritz** [comment]
@ttg-team-web  can you test https://github.com/b13/container/commit/2b6917cdc05ae1ab6731a6ddfc90f3ec555469f3

**Comment by wolfhoel** [comment]
@achimfritz i've tested https://github.com/b13/container/commit/2b6917cdc05ae1ab6731a6ddfc90f3ec555469f3 and now everything works as expected. Thank you!
