### ISSUE TITLE
setGroup with Localized String

### ISSUE THREAD

**Issue by domjos1994** [b13/container#448]
Hello,
is there a way to add a localized String in setGroup?
Like: setGroup('LLL:<path>/container.xlf:<key>')

**Comment by bmack** [comment]
Hey @domjos1994 ,

the group is a string identifier, where the label is added separately, and a new group should be added like this:
https://docs.typo3.org/m/typo3/reference-tca/12.4/en-us/ColumnsConfig/Type/Select/Properties/ItemGroups.html#confval-itemGroups

**Comment by domjos1994** [comment]
I found a solution.
Thanks for the support
