### ISSUE TITLE
Sorting of content-elements in list-view not working in TYPO3 12

### ISSUE THREAD

**Issue by stephangrass** [b13/container#451]
When trying to sort content elements in the list view using the arrow keys, the following error appears:

Cannot access offset of type string on string
in /var/www/html/vendor/b13/container/Classes/Hooks/Datahandler/CommandMapBeforeStartHook.php line 132

But sorting the second element upwards seems to always work..

**Comment by achimfritz** [comment]
Hi @stephangrass , can you explain, how this is reproducable on an TYPO3/container Vanilla instance? (did you run the "container:sorting --apply" command? )

**Comment by stephangrass** [comment]
Hi @achimfritz, maybe this happends after updating to 12.4.7. 

In an old TYPO3 12.2.0 (only container installed), I couldn't reproduce the error. Only after updating to 12.4.7. The command container:sorting --apply doesn't help either.

Strangely enough, it's possible to move the second element of the list upwards...
![2023-10-13_08-56-22](https://github.com/b13/container/assets/4489147/c711429b-6a9a-4e56-9e05-4d42f87725a6)
![2023-10-13_08-56-57](https://github.com/b13/container/assets/4489147/383e5ec7-e051-46da-8a53-2f71777a677a)

**Comment by stephangrass** [comment]
I believe the error appears after an update to TYPO3 12.4.7. In a 12.4.6 instance, the sorting works, but after the update to 12.4.7, it no longer does...

**Comment by achimfritz** [comment]
hm, ok, got it, i will care, thanks for reporting
