### ISSUE TITLE
Container colPos lost due to JavaScript rounding

### ISSUE THREAD

**Issue by mbrodala** [b13/container#456]
Another one for the dreaded `colPos` topic (https://github.com/b13/container/issues/443): given either a container record with a large UID or a container `colPos` with a large number, the resulting `colPos` in the TYPO3 markup may be rounded due to the `parseInt()` call here:

https://github.com/TYPO3/typo3/blob/8f8f9344029cc0afaaea705f771e2e0b479b5ae1/Build/Sources/TypeScript/backend/layout-module/drag-drop.ts#L298

Example:

* Container UID: `2944`
* Container `colPos`: `1643883724`

|Type|Value|
|-|-|
|Outputted `colPos`|`29449999901643883724`|
|**Used `colPos`**, `parseInt("29449999901643883724")`|`29449999901643882000`|

Here the original `colPos` of `1643883724` was basically converted to `1643882000` due to integer limits in JavaScript.

While one can try to work around this by reducing/cutting off the container `colPos`, the issue will occur again with containers having large UIDs.

So IMO this needs a different/proper solution.

**Comment by Sa-Lat** [comment]
just found out, that there's a branch for this problem:

https://github.com/b13/container/compare/master...task/colpos-parent

When I use this one, it actually solves our Problem.

**Comment by MaxAmann-sitegeist** [comment]
> just found out, that there's a branch for this problem:
> 
> [master...task/colpos-parent](https://github.com/b13/container/compare/master...task/colpos-parent)
> 
> When I use this one, it actually solves our Problem.

We have the same Problem.
Can we somehow help with testing and merging to fix the error?
