### ISSUE TITLE
Since the latest update to version 2.3.0, it is no longer possible to sort the elements within a container.

### ISSUE THREAD

**Issue by kbenyedder** [b13/container#463]
Prior to the update, it was possible to change the order of elements within a container by dragging and dropping them to the desired position. However, after the update, this functionality is no longer available. There is no way to sort the elements anymore, and they retain their original order.

**Comment by achimfritz** [comment]
Hi @kbenyedder , did you rerun the container:sorting command (s. https://github.com/b13/container/releases/tag/2.3.0)

**Comment by achimfritz** [comment]
@kbenyedder  any news?
