### ISSUE TITLE
TYPO3 v12 Container Drag & Drop results in unused elements in BE

### ISSUE THREAD

**Issue by TonyMarc** [b13/container#464]
Similar to but not the same issue as #443 since I am running a 64 Bit System.
I am currently on v2.3.1 of the EXT:container.

When dragging and dropping content elements from containers they become unused elements in the TYPO3 BE. This only occurs with elements and containers with UIDs like 1692168415 (all of my UIDs on production are timestamps in fact). I testet this locally with fixtures and smaller UIDs (100-1000) which works fine.

**Comment by Teddytrombone** [comment]
Same problem here but my uids are smaller. When downgrading to 2.3.0 it works again.

**Comment by Teddytrombone** [comment]
I tested the new version 2.3.2 and it seems the problem is gone

**Comment by TonyMarc** [comment]
I updated EXT:container to v2.3.2, the problem is still there. 

Upon further investigation: Those unused elements get a wrong colPos after moving them from one container to another. In my case the get a 300 colPos instead of 200.

**Comment by Sa-Lat** [comment]
I can narrow it down to the same problem as here: https://github.com/b13/container/issues/456

**Comment by mark-kirstein** [comment]
Still having this issue in 2.3.6 in several installations. Is there any possiblility to fix this?

**Comment by Sa-Lat** [comment]
As far as I can see, there is no tag for this fix at the moment.

**Comment by mark-kirstein** [comment]
Sorry answering again, but does this means somebody is working on it and it will be fixed in near future?

**Comment by mark-kirstein** [comment]
Ok i checked the installation again and recognized i'm using a custom partial for PageLayout/Gris/Column. After deleting it's working again.
