### ISSUE TITLE
TYPO3 Deprecation Notice: QueryBuilder::execute()

### ISSUE THREAD

**Issue by SSFGizmo** [b13/container#465]
`TYPO3 Deprecation Notice: QueryBuilder::execute() will be removed in TYPO3 v13.0. 
Use executeQuery() or executeStatement() directly. 
in /var/www/html/vendor/typo3/cms-core/Classes/Database/Query/QueryBuilder.php line 254 `

Is it possible to call 'execute()' under the condition and add executeQuery() for other cases?

```
if ((GeneralUtility::makeInstance(Typo3Version::class))->getMajorVersion() === 10) {
    return (array)$stm->execute()->fetchAll();
}

return (array)$stm->executeQuery()->fetchAllAssociative();
```

**Comment by achimfritz** [comment]
this is fixed in current release 2.3.2 (https://github.com/b13/container/commit/d0d6774355b943d582e9766b92fd431a7affaaa7)
