### ISSUE TITLE
Getting error in history/undo after moving content elements

### ISSUE THREAD

**Issue by m-kappenberg** [b13/container#472]
Same as/duplicates: https://github.com/b13/container/issues/467
Sorry, found the above one, after submitting this issue, maybe remove my issue.

Container Version 2.3.1, TYPO3 12.4.10, PHP version: 8.1.26
Steps to reproduce here:
Move/drag a content element in a container element/column
Go to History/Undo
Then the following warning comes up:
An error occurred trying to process items for field "Container" (PHP Warning: Undefined array key "tx_container_parent" in /.../typo3conf/ext/container/Classes/Tca/ItemProcFunc.php line 51).
An error occurred trying to process items for field "Container" (PHP Warning: Undefined array key "tx_container_parent" in /.../typo3conf/ext/container/Classes/Tca/ItemProcFunc.php line 83).

Local fix here:
../container/Classes/Tca/ItemProcFunc.php, there lines 51 and 83
from:
    if ($row['tx_container_parent'] > 0)
to:
    if (isset($row['tx_container_parent']) && $row['tx_container_parent'] > 0)

**Comment by achimfritz** [comment]
should be fixed in 2.3.3 with https://github.com/b13/container/commit/2ef3fd19c9c5a71c25a92420e26e2d46808ea358
