### ISSUE TITLE
Content-Elements with sys_language_uid === -1 are only shown in the language they're in

### ISSUE THREAD

**Issue by BeerOnTheBeach** [b13/container#478]
**Description**
Content-Elements inside b13-containers are not shown in other languages if the language is set to "all languages".

**How to reproduce**
Could reproduce it in a fresh TYPO3 v11.5.35 installation with only the b13/container (2.3.5) and the b13/container-example (2.0.0) installed.

1. Add another language
2. Create a container, add Content-Element
3. Set both to language "All languages"

![image](https://github.com/b13/container/assets/58625187/ffe101a2-4a42-48ee-a69a-5542a9eba006)

**Solution approach**

Not sure if I'm on the correct path here, but I've noticed that the container/Classes/Domain/Factory/PageView/Frontend/ContainerFactory.php:95 is only checking if the language is > 0. Checking if the record-language is -1 would fix this. Testing this seemed to not break anything, but I'm not 100% sure tbh.

This would be the diff:

``` patch
--- public/typo3conf/ext/container/Classes/Domain/Factory/PageView/Frontend/ContainerFactory.php
+++ public/typo3conf/ext/container/Classes/Domain/Factory/PageView/Frontend/ContainerFactory.php
@@ -92,7 +92,7 @@
         }

         $defaultRecord = null;
-        if ($record['sys_language_uid'] > 0) {
+        if ($record['sys_language_uid'] > 0 || $record['sys_language_uid'] === -1) {
             $defaultRecord = $this->defaultContainer($record);
             if ($defaultRecord === null) {
                 // free mode
```

**Comment by chesio** [comment]
Hi @BeerOnTheBeach, this is not supported - see #237.

**Comment by BeerOnTheBeach** [comment]
hi @chesio, 

thanks for the hint. Seems this is never gonna happen then, huh?

**Comment by wolfgang007** [comment]
@BeerOnTheBeach do you found a solution / workaround for this?

Or what is your final way for this? I have the same problem at the moment. 

Thx for your response.

**Comment by achimfritz** [comment]
Hi Guys, i close this issue, because sys_language_uid=-1 is not (and will not) supported. (We wait for a better solution in the TYPO3-Core)
