### ISSUE TITLE
Error when I try to execute the upgrade wizard "EXT:container: Migrate "container" sorting" with TYPO3 V12

### ISSUE THREAD

**Issue by Oktopuce** [b13/container#488]
When I tried to run the upgrade wizard "**EXT:container: Migrate "container" sorting**" through the TYPO3 BE with TYPO3 V12, the following exception is thrown: 

```
(1/1) RuntimeException
Unable to call method "getNormalizedParams" of non-object "request".
```

- TYPO3: 12.4.12
- PHP: 8.2
- b13/container: 2.3.5

Same problem with upgrade wizard "**EXT:container: Delete "container" children whith wrong pid**"

**Comment by mbrodala** [comment]
This is likely an error in your TypoScript, see https://docs.typo3.org/m/typo3/reference-typoscript/12.4/en-us/Conditions/Index.html#request-getqueryparams
