### ISSUE TITLE
Option setBackendTemplate is missing

### ISSUE THREAD

**Issue by pixelbreit** [b13/container#495]
I noticed that in the current documentation the option setBackendTemplate is no longer listed.

Maybe I just overlooked it, but will the option be removed in the future and if so, how can you still assign a backend template?

**Comment by achimfritz** [comment]
this is because it is never used, because we dropped TYPO3 v10 Support and thus non "fluid-page-module" PageRendering in Backend.
Code in ContainerConfiguration needs regading backendTemplate needs to be removed

**Comment by achimfritz** [comment]
i wonder if i was was drunken, when i removed the backend-template?
