### ISSUE TITLE
Error in upgrade wizard "EXT:container: Migrate "container" sorting" in TYPO3 12.4.15

### ISSUE THREAD

**Issue by w010** [b13/container#501]
Wizard: EXT:container: Migrate "container" sorting

TYPO3: 12.4.15
PHP: 8.1
b13/container: 2.3.6

(Problem is similar to one closed issue, but the error is different, so it's not a duplicate.)
Cannot apply the wizard, because error is thrown on each try:

```
 TypeError
TYPO3\CMS\Core\Http\ApplicationType::fromRequest(): Argument #1 ($request) must be of type Psr\Http\Message\ServerRequestInterface, null given, called in /var/www/html/public/typo3conf/ext/dce/Classes/Components/TemplateRenderer/StandaloneViewFactory.php on line 143

in /var/www/html/public/typo3_src-12.4.15/typo3/sysext/core/Classes/Http/ApplicationType.php line 67
```

When deactivating ext DCE, then the error comes from Powermail, etc..:
```
/1) TypeError
In2code\Powermail\EventListener\FlexFormParsingModifyEventListener::getRequest(): Return value must be of type Psr\Http\Message\ServerRequestInterface, null returned
```

**Comment by stephangrass** [comment]
similar here:


(1/1) TypeError
`
TYPO3\CMS\Core\Routing\BackendEntryPointResolver::getUriFromRequest(): Argument #1 ($request) must be of type Psr\Http\Message\ServerRequestInterface, null given, called in /var/www/html/vendor/typo3/cms-core/Classes/Authentication/BackendUserAuthentication.php on line 2089`

**Comment by mschwemer** [comment]
DCE is also fixed: https://github.com/a-r-m-i-n/dce/issues/105

**Comment by achimfritz** [comment]
@mschwemer  thanks
