### ISSUE TITLE
Feature: Display elements nested in list view

### ISSUE THREAD

**Issue by artus70** [b13/container#506]
I remember that I once had a nested view of grid elements (extension gridelements) in TYPO3 where the grid containers could even be expanded and collapsed. This was **very** helpful in order not to lose track of the many elements.

Could this be achieved in container also?

(Sorry if this topic may already have been discussed somewhere.)

**Comment by chesio** [comment]
> Sorry if this topic may already have been discussed somewhere.

If you mean collapsing of elements, then yes - it has been requested already: https://github.com/b13/container/issues/123

**Comment by artus70** [comment]
> If you mean collapsing of elements, then yes - it has been requested already: #123

You seem to be talking about the display in _page view_ which is also a reasonable demand, but I'm talking about _list view_ where nested elements would get displayed as sub-ordered elements of the grid containers, and the grid containers then could get collapsed to conceal the contained elements. The gridelements extension did this quite well.

I think this ist senseful because the contained elements actually are not placed at top-level of the page column but sub-ordered to another element (grid container).

**Comment by achimfritz** [comment]
sorry, list-view is not supported by this extension
