### ISSUE TITLE
Registry: Global disallow setting

### ISSUE THREAD

**Issue by saitho** [b13/container#507]
We have a few containers defined across multiple extensions and we have many content elements.
Some content elements are not suited to be nested in containers, therefore we want to exclude those from all containers.

Right now there is no way to exclude a content element from all grids. I'd like to suggest a new method for the container Registry that allows defining a global disallow setting, that is merged with the disallow list already returned by `Registry::getContentDefenderConfiguration`.

```php
Registry::addDisallowedCType(string $cType): void
```

Maybe a content element globally disallowed via this method, should only be allowed when it is explicitly listed in "allowed".

**Comment by achimfritz** [comment]
see my comment in your PR https://github.com/b13/container/pull/508#issuecomment-2395074535
