### ISSUE TITLE
Sorting does not work when child item is moved to first position in container

### ISSUE THREAD

**Issue by flixflax** [b13/container#522]
Hi,

I noticed that there seems to be an issue with sorting when one moves a content element positioned in a container-element to the very first position of this container element.

Following environment is used:

- TYPO3 11.5.38
- ext:container v2.3.6

I positioned multiple text-elements in one container element. Everything worked well. Then I tried to move the very last text-element to the very first position. It seemed to work, but after reloading the page in backend, the moving was undone. 

Then I debugged the code and found that in this scenario the **UID of the container** is used to fetch the sorting-number. When the text-element is moved to the second position, the **UID of the preceding text-element** is used to fetch the sorting-number.

I had to downgrade to v1.6.1 to get rid of this issue, as it exists in all versions of v2.

**Comment by achimfritz** [comment]
Hi @flixflax , did you run the container sorting fix commands?

`./vendor/bin/typo3cms container:sorting --apply`
and `./vendor/bin/typo3cms container:sorting-in-page --apply`

(https://github.com/b13/container/releases/tag/2.0.0)

did you upgrade to 2.x?

**Comment by flixflax** [comment]
Hi @achimfritz,

thank you for pointing out, that the commands have to be executed even if one does not upgrade but use directly v2. I was able to test this in my development environment and it seems to fix my issue. 👍🏼
