### ISSUE TITLE
Interface "TYPO3\CMS\Install\Updates\UpgradeWizardInterface" not found

### ISSUE THREAD

**Issue by xperseguers** [b13/container#525]
Just kickstarted migrating to TYPO3 v13 and I had a main `composer.json` without a reference to `"typo3/cms-install"`.

This is supposed to be optional now, but if that package is not present, the Backend breaks with the error:

```
Interface "TYPO3\CMS\Install\Updates\UpgradeWizardInterface" not found
```

This is raised by `Classes/Updates/ContainerMigrateSorting.php:28`

**Comment by d-g-codappix** [comment]
We could fix this in our tests by adding `typo3/cms-install` to the dev dependencies.
We would remove this later and only install this extension in ci, because we do not need the extension in our dev environment.

**Comment by achimfritz** [comment]
fixed with https://github.com/b13/container/pull/532
