### ISSUE TITLE
Make Container collabsible

### ISSUE THREAD

**Issue by criwe** [b13/container#531]
Hi!

to have more clarity in the backend, it would be great if the containers were expandable/collapsible
There is an extension (https://github.com/evoWeb/ew_collapsible_container/), but imho such a function should be integrated directly, as it is essential for the usability and clarity.

Many greetings,
Christoph

**Comment by chesio** [comment]
Hi @criwe, this has already been requested before: https://github.com/b13/container/issues/123

**Comment by criwe** [comment]
Oh, thanks! I´ll close that one.
