### ISSUE TITLE
Description for containers is not shown

### ISSUE THREAD

**Issue by Xathos1991** [b13/container#535]
Hi, I tried the ContainerConfiguration as shown in the readme but the Description is not shown below the label for containers. I think the issue might be that the description is not set in Registry.php configureContainer function add there's not getDescription() function to ContainerConfiguration.php

**Comment by achimfritz** [comment]
Hi @Xathos1991 , the description is only for the new content element wizard. Where do you miss it? (what TYPO3-Version)

**Comment by Kleini13** [comment]
Hi, I have the same problem.  The description is not shown in the "New Page Content" wizard. In addition, the icon is not visible in the wizard, but is visible within the content element (Type[CType]).
– TYPO3 (13.4.0-dev)
– Container Content Elements  (dev-master)
<img width="999" alt="Bildschirmfoto 2024-09-25 um 15 03 02" src="https://github.com/user-attachments/assets/6bdfbd27-da91-471e-bf23-35765189d559">
<img width="690" alt="Bildschirmfoto 2024-09-25 um 15 03 10" src="https://github.com/user-attachments/assets/fdc162e6-ee8f-4726-9c88-1e855f65c320">

**Comment by achimfritz** [comment]
you are right, thanks, i will fix it

but icon is shown, may be the configuration in your example is wrong?

![Screenshot 2024-10-02 at 18 00 09](https://github.com/user-attachments/assets/67c3847f-f608-48f0-8844-dcc32ac7b8d9)
