### ISSUE TITLE
Template name in lower case does not work

### ISSUE THREAD

**Issue by Kleini13** [b13/container#536]
If the template name is written with a lowercase letter at the beginning, the template is not found because it automatically assumes an uppercase letter. See Typo3 error message below. 

- TYPO3 [13.4.0-dev]
- Content Container [dev-master]

```
(1/1) #1257246929 TYPO3Fluid\Fluid\View\Exception\InvalidTemplateResourceException

Tried resolving a template file for controller action "Default->Container-3col" in format ".html", but none of the paths contained the expected template file (Default/Container-3col.html). The following paths were checked: /var/www/html/vendor/typo3/cms-fluid-styled-content/Resources/Private/Templates/, /var/www/html/vendor/atelier26/foundation26/Resources/Private/Templates/ContentElements/
```

**Comment by achimfritz** [comment]
not a container issue, Fluid Templates needs always start with an uppercase letter

**Comment by Kleini13** [comment]
@achimfritz Thanks for the information. My bad.
