### ISSUE TITLE
Restrict "Create New" wizard button to content defender allowed elements

### ISSUE THREAD

**Issue by baschny** [b13/container#537]
Having a container setup using content_defender to restrict certain containers to certain content elements.

In the Web>Page view the editor has two ways of creating new content:

(1) `+ Content` button
(2) the "More options..." > `'Create New' wizard` from the context menu

<img width="646" alt="container-buttons" src="https://github.com/user-attachments/assets/90339984-992a-44b6-9f4c-50519bc5f86b">

Using the first option restricts the content elements as expected:

<img width="985" alt="container-restricted" src="https://github.com/user-attachments/assets/a12cd69a-d5b3-4fe2-badc-1b98786a3f52">

Using the second option (the "wizard" from the context menu), the editor is presented with a list of all available content elements:

<img width="966" alt="container-all" src="https://github.com/user-attachments/assets/c1b78d24-617f-477e-a5f4-68814103679f">

This should be the same list.

Another (maybe easier) option would be to simply remove the context menu item, because its redundant anyway.

**Comment by thomasrawiel** [comment]
The context menu adds a new Content Element to the page, not the container - so the list of all available content elements would be correct if you haven't restricted your page's backend_layout

**Comment by thomasrawiel** [comment]
Ah I see what you mean - just tested this and can confirm, the list of available types is not correct if you click the context menu on an element inside a container

**Comment by thomasrawiel** [comment]
To add, I think the problem lies in EXT:content_defenders WizardItemsHook, which only checks backend_layouts

**Comment by thomasrawiel** [comment]
@baschny added a PR (works for me now with content-defender), can you test that?

**Comment by baschny** [comment]
@thomasrawiel works great, thanks!

**Comment by achimfritz** [comment]
fixed with https://github.com/b13/container/pull/541
