### ISSUE TITLE
TYPO3 13: Drag & Drop into containers doesn't work

### ISSUE THREAD

**Issue by einNicklas** [b13/container#552]
TYPO3: 13.4.0
container: 3.0.0

It does not appear to be possible to drag elements into a drop zone apart from the first one:

![Screenshot_20241107_124320](https://github.com/user-attachments/assets/233620a5-c0e6-4b64-9d93-2b07808e6b78)

The elements have the correct colPos, but no tx_container_parent:

![Screenshot_20241107_124940@2x](https://github.com/user-attachments/assets/d678a8dd-6963-4165-a77c-0b7b39da70fc)

… instead of:

![Screenshot_20241107_125015@2x](https://github.com/user-attachments/assets/f75c1fa2-8608-46af-bf82-d36001f5631d)

**Comment by einNicklas** [comment]
No worries, and thanks a lot for the quick fix! Really appreciate your fast response. :)

**Comment by maximaexchen** [comment]
Sorry, but I have this same problem with 

```
"b13/container": "^3.1",
"typo3/cms-core": "^13.4",
```
After drag & drop the "tx_container_parent" becomes 0

Could this be a configutation problem too?
