### ISSUE TITLE
Workspace Preview shows Workspace Content in Live Section

### ISSUE THREAD

**Issue by tlayh** [b13/container#558]
As a starting point I added some content to the Live Workspace, then I created a 1-cell grid on this page. Inside this 1-cell grid there is only a single text element.

I am working with TYPO3 v12.

After switching to the workspace view in the backend and changing the text element, I noticed that the Workspace Preview shows the content from the workspace inside the live part. The elements {child.header} and {child.bodytext} inside the template are showing the unpublished content from the Workspace instead of the published content. The element {child.renderedContent} shows the correct content.

I attached two screens from the backend and the result in the frontend for better understanding with some additional notes.
![container-draftWorkspace-backend](https://github.com/user-attachments/assets/1200ff7c-4f90-4fb7-94ab-61ef15a5071e)

![Frontend-Preview](https://github.com/user-attachments/assets/5b04f2c6-5749-48ea-8c6d-65e0bfda4e32)

HTML-Template:
```
<div class="one-cell">
    <f:if condition="{children}">
        <div class="left-children">
            <f:for each="{children}" as="child">
                <p>uid: {child.uid}</p>
                <p>t3ver_oid: {child.t3ver_oid}</p>
                <p>tx_container_parent: {child.tx_container_parent}</p>
                Header: {child.header}<br />
                Body {child.bodytext}
                <h5>Rendered Content</h5>
                <f:format.raw>{child.renderedContent}</f:format.raw>
            </f:for>
        </div>
    </f:if>
</div>
```

TypoScript:
```
tt_content.b13-1col < lib.contentElement
tt_content.b13-1col {
  templateName = 1Col
  templateRootPaths.10 = EXT:container_example/Resources/Private/Templates
  dataProcessing {
    200 = B13\Container\DataProcessing\ContainerProcessor
    200 {
      colPos = 200
      as = children
    }
  }
}
```

TCA Overwrite:
```
\TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance(\B13\Container\Tca\Registry::class)->configureContainer(
    (
        new \B13\Container\Tca\ContainerConfiguration(
            'b13-1col', // CType
            '1 Column', // label
            'Some Description of the Container', // description
            [
                [
                    ['name' => '1-col', 'colPos' => 200]
                ]
            ] // grid configuration
        )
    )
);
```

Thank you for looking into it.

**Comment by tlayh** [comment]
Just found out that is our own rendering definitions that destroy everything. We just tested this case with a plane v12 and v13 installation and everything works fine.

Closing this issue now ;)

**Comment by sorenmalling** [comment]
@tlayh Can you elaborate what in your rendering definitions that destroyed everything? I do seem to be facing the issue you describe and would love a pointer :)
