### ISSUE TITLE
Migrate "container" sorting fails, Typo3 12.4.23, PHP 8.1

### ISSUE THREAD

**Issue by topsnet-holgerd** [b13/container#561]
**PHP 8.2 solved this, you can close it this issue!**

In Debug Mode, I get the stack trace below, in Live Mode I'm getting 503 Error

(1/1) #1476107295 TYPO3\CMS\Core\Error\Exception

PHP Warning: Undefined array key "host" in typo3_src-12.4.23/vendor/symfony/expression-language/Node/GetAttrNode.php line 133
in typo3_src-12.4.23/typo3/sysext/core/Classes/Error/ErrorHandler.php line 141

        }

        $message = self::ERROR_LEVEL_LABELS[$errorLevel] . ': ' . $errorMessage . ' in ' . $errorFile . ' line ' . $errorLine;
        if ($errorLevel & $this->exceptionalErrors) {
            throw new Exception($message, 1476107295);
        }

        $message = $this->getFormattedLogMessage($message);

at TYPO3\CMS\Core\Error\ErrorHandler->handleError()
in typo3_src-12.4.23/vendor/symfony/expression-language/Node/GetAttrNode.php line 133

                if ($this->attributes['is_null_coalesce']) {
                    return $array[$this->nodes['attribute']->evaluate($functions, $values)] ?? null;
                }

                return $array[$this->nodes['attribute']->evaluate($functions, $values)];
        }
    }

    private function isShortCircuited(): bool

at Symfony\Component\ExpressionLanguage\Node\GetAttrNode->evaluate()
in typo3_src-12.4.23/vendor/symfony/expression-language/Node/GetAttrNode.php line 119

                return $toCall(...array_values($this->nodes['arguments']->evaluate($functions, $values)));

            case self::ARRAY_CALL:
                $array = $this->nodes['node']->evaluate($functions, $values);

                if (null === $array && $this->isShortCircuited()) {
                    return null;
                }

at Symfony\Component\ExpressionLanguage\Node\GetAttrNode->evaluate()
in typo3_src-12.4.23/vendor/symfony/expression-language/Node/BinaryNode.php line 98

    public function evaluate(array $functions, array $values): mixed
    {
        $operator = $this->attributes['operator'];
        $left = $this->nodes['left']->evaluate($functions, $values);

        if (isset(self::FUNCTIONS[$operator])) {
            $right = $this->nodes['right']->evaluate($functions, $values);

at Symfony\Component\ExpressionLanguage\Node\BinaryNode->evaluate()
in typo3_src-12.4.23/vendor/symfony/expression-language/Node/BinaryNode.php line 98

    public function evaluate(array $functions, array $values): mixed
    {
        $operator = $this->attributes['operator'];
        $left = $this->nodes['left']->evaluate($functions, $values);

        if (isset(self::FUNCTIONS[$operator])) {
            $right = $this->nodes['right']->evaluate($functions, $values);

at Symfony\Component\ExpressionLanguage\Node\BinaryNode->evaluate()
in typo3_src-12.4.23/vendor/symfony/expression-language/ExpressionLanguage.php line 59

     * Evaluate an expression.
     */
    public function evaluate(Expression|string $expression, array $values = []): mixed
    {
        return $this->parse($expression, array_keys($values))->getNodes()->evaluate($this->functions, $values);
    }

    /**
     * Parses an expression.

at Symfony\Component\ExpressionLanguage\ExpressionLanguage->evaluate()
in typo3_src-12.4.23/typo3/sysext/core/Classes/ExpressionLanguage/Resolver.php line 73

     * Evaluate an expression.
     */
    public function evaluate(string $expression, array $contextVariables = []): mixed
    {
        return $this->expressionLanguage->evaluate($expression, array_replace($this->expressionLanguageVariables, $contextVariables));
    }

    /**
     * Compiles an expression to source code.

at TYPO3\CMS\Core\ExpressionLanguage\Resolver->evaluate()
in typo3_src-12.4.23/typo3/sysext/core/Classes/TypoScript/IncludeTree/Visitor/IncludeTreeConditionMatcherVisitor.php line 164

            return;
        }
        $conditionExpression = $include->getConditionToken()->getValue();
        try {
            $verdict = (bool)$this->resolver->evaluate($conditionExpression);
        } catch (SyntaxError) {
            $this->logger->error('Expression could not be parsed.', ['expression' => $conditionExpression]);
            $verdict = false;
        }

at TYPO3\CMS\Core\TypoScript\IncludeTree\Visitor\IncludeTreeConditionMatcherVisitor->visitBeforeChildren()
in typo3_src-12.4.23/typo3/sysext/core/Classes/TypoScript/IncludeTree/Traverser/ConditionVerdictAwareIncludeTreeTraverser.php line 55

    private function traverseRecursive(IncludeInterface $include, array $visitors, int $currentDepth): void
    {
        foreach ($visitors as $visitor) {
            $visitor->visitBeforeChildren($include, $currentDepth);
        }
        if ($include instanceof IncludeConditionInterface && !$include->getConditionVerdict()) {
            // Don't traverse children if condition did not match.
            return;

at TYPO3\CMS\Core\TypoScript\IncludeTree\Traverser\ConditionVerdictAwareIncludeTreeTraverser->traverseRecursive()
in typo3_src-12.4.23/typo3/sysext/core/Classes/TypoScript/IncludeTree/Traverser/ConditionVerdictAwareIncludeTreeTraverser.php line 62

            // Don't traverse children if condition did not match.
            return;
        }
        foreach ($include->getNextChild() as $child) {
            $this->traverseRecursive($child, $visitors, $currentDepth + 1);
            foreach ($visitors as $visitor) {
                $visitor->visit($child, $currentDepth);
            }
        }

at TYPO3\CMS\Core\TypoScript\IncludeTree\Traverser\ConditionVerdictAwareIncludeTreeTraverser->traverseRecursive()
in typo3_src-12.4.23/typo3/sysext/core/Classes/TypoScript/IncludeTree/Traverser/ConditionVerdictAwareIncludeTreeTraverser.php line 62

            // Don't traverse children if condition did not match.
            return;
        }
        foreach ($include->getNextChild() as $child) {
            $this->traverseRecursive($child, $visitors, $currentDepth + 1);
            foreach ($visitors as $visitor) {
                $visitor->visit($child, $currentDepth);
            }
        }

at TYPO3\CMS\Core\TypoScript\IncludeTree\Traverser\ConditionVerdictAwareIncludeTreeTraverser->traverseRecursive()
in typo3_src-12.4.23/typo3/sysext/core/Classes/TypoScript/IncludeTree/Traverser/ConditionVerdictAwareIncludeTreeTraverser.php line 62

            // Don't traverse children if condition did not match.
            return;
        }
        foreach ($include->getNextChild() as $child) {
            $this->traverseRecursive($child, $visitors, $currentDepth + 1);
            foreach ($visitors as $visitor) {
                $visitor->visit($child, $currentDepth);
            }
        }

at TYPO3\CMS\Core\TypoScript\IncludeTree\Traverser\ConditionVerdictAwareIncludeTreeTraverser->traverseRecursive()
in typo3_src-12.4.23/typo3/sysext/core/Classes/TypoScript/IncludeTree/Traverser/ConditionVerdictAwareIncludeTreeTraverser.php line 62

            // Don't traverse children if condition did not match.
            return;
        }
        foreach ($include->getNextChild() as $child) {
            $this->traverseRecursive($child, $visitors, $currentDepth + 1);
            foreach ($visitors as $visitor) {
                $visitor->visit($child, $currentDepth);
            }
        }

at TYPO3\CMS\Core\TypoScript\IncludeTree\Traverser\ConditionVerdictAwareIncludeTreeTraverser->traverseRecursive()
in typo3_src-12.4.23/typo3/sysext/core/Classes/TypoScript/IncludeTree/Traverser/ConditionVerdictAwareIncludeTreeTraverser.php line 49

                    1689244840
                );
            }
        }
        $this->traverseRecursive($rootInclude, $visitors, 0);
    }

    private function traverseRecursive(IncludeInterface $include, array $visitors, int $currentDepth): void
    {

at TYPO3\CMS\Core\TypoScript\IncludeTree\Traverser\ConditionVerdictAwareIncludeTreeTraverser->traverse()
in typo3_src-12.4.23/typo3/sysext/extbase/Classes/Configuration/BackendConfigurationManager.php line 305

        $includeTreeTraverserConditionVerdictAwareVisitors[] = $setupMatcherVisitor;
        $setupAstBuilderVisitor = GeneralUtility::makeInstance(IncludeTreeAstBuilderVisitor::class);
        $setupAstBuilderVisitor->setFlatConstants($flatConstants);
        $includeTreeTraverserConditionVerdictAwareVisitors[] = $setupAstBuilderVisitor;
        $this->includeTreeTraverserConditionVerdictAware->traverse($setupIncludeTree, $includeTreeTraverserConditionVerdictAwareVisitors);
        $setupAst = $setupAstBuilderVisitor->getAst();

        $setupArray = $setupAst->toArray();

at TYPO3\CMS\Extbase\Configuration\BackendConfigurationManager->getTypoScriptSetup()
in /var/www/clients/client49/web207/web/typo3_src-12.4.23/typo3/sysext/extbase/Classes/Configuration/BackendConfigurationManager.php line 320

     * Returns the TypoScript configuration found in config.tx_extbase
     */
    protected function getExtbaseConfiguration(): array
    {
        $setup = $this->getTypoScriptSetup();
        $extbaseConfiguration = [];
        if (isset($setup['config.']['tx_extbase.'])) {
            $extbaseConfiguration = $this->typoScriptService->convertTypoScriptArrayToPlainArray($setup['config.']['tx_extbase.']);
        }

at TYPO3\CMS\Extbase\Configuration\BackendConfigurationManager->getExtbaseConfiguration()
in typo3_src-12.4.23/typo3/sysext/extbase/Classes/Configuration/BackendConfigurationManager.php line 171

        // @todo: Avoid $GLOBALS['TYPO3_REQUEST'] in v13.
        /** @var ServerRequestInterface|null $request */
        $request = $this->request ?? $GLOBALS['TYPO3_REQUEST'] ?? null;

        $frameworkConfiguration = $this->getExtbaseConfiguration();
        if (!isset($frameworkConfiguration['persistence']['storagePid'])) {
            $frameworkConfiguration['persistence']['storagePid'] = $this->getCurrentPageId($request);
        }
        // only merge $this->configuration and override controller configuration when retrieving configuration of the current plugin

at TYPO3\CMS\Extbase\Configuration\BackendConfigurationManager->getConfiguration()
in typo3_src-12.4.23/typo3/sysext/extbase/Classes/Configuration/ConfigurationManager.php line 140

    public function getConfiguration(string $configurationType, ?string $extensionName = null, ?string $pluginName = null): array
    {
        switch ($configurationType) {
            case self::CONFIGURATION_TYPE_SETTINGS:
                $configuration = $this->concreteConfigurationManager->getConfiguration($extensionName, $pluginName);
                return $configuration['settings'] ?? [];
            case self::CONFIGURATION_TYPE_FRAMEWORK:
                return $this->concreteConfigurationManager->getConfiguration($extensionName, $pluginName);
            case self::CONFIGURATION_TYPE_FULL_TYPOSCRIPT:

at TYPO3\CMS\Extbase\Configuration\ConfigurationManager->getConfiguration()
in typo3_src-12.4.23/typo3/sysext/form/Classes/Mvc/Configuration/ConfigurationManager.php line 180

     */
    protected function getTypoScriptSettings(string $extensionName)
    {
        return parent::getConfiguration(
            ConfigurationManagerInterface::CONFIGURATION_TYPE_SETTINGS,
            $extensionName
        );
    }
}

at TYPO3\CMS\Form\Mvc\Configuration\ConfigurationManager->getTypoScriptSettings()
in /var/www/clients/client49/web207/web/typo3_src-12.4.23/typo3/sysext/form/Classes/Mvc/Configuration/ConfigurationManager.php line 98

                1471473377
            );
        }

        $typoscriptSettings = $this->getTypoScriptSettings($extensionName);

        $yamlSettingsFilePaths = isset($typoscriptSettings['yamlConfigurations'])
            ? ArrayUtility::sortArrayWithIntegerKeys($typoscriptSettings['yamlConfigurations'])
            : [];

at TYPO3\CMS\Form\Mvc\Configuration\ConfigurationManager->getConfigurationFromYamlFile()
in typo3_src-12.4.23/typo3/sysext/form/Classes/Mvc/Configuration/ConfigurationManager.php line 66

    public function getConfiguration(string $configurationType, ?string $extensionName = null, ?string $pluginName = null): array
    {
        switch ($configurationType) {
            case self::CONFIGURATION_TYPE_YAML_SETTINGS:
                return $this->getConfigurationFromYamlFile($extensionName);
            default:
                return parent::getConfiguration($configurationType, $extensionName, $pluginName);
        }
    }

at TYPO3\CMS\Form\Mvc\Configuration\ConfigurationManager->getConfiguration()
in typo3_src-12.4.23/typo3/sysext/form/Classes/Mvc/Persistence/FormPersistenceManager.php line 89

            $request = (new ServerRequest())->withAttribute('applicationType', SystemEnvironmentBuilder::REQUESTTYPE_BE);
            $GLOBALS['TYPO3_REQUEST'] = $request;
            $fakeRequest = true;
        }
        $this->formSettings = $configurationManager->getConfiguration(ConfigurationManagerInterface::CONFIGURATION_TYPE_YAML_SETTINGS, 'form');
        $this->typoScriptSettings = $configurationManager->getConfiguration(ConfigurationManagerInterface::CONFIGURATION_TYPE_SETTINGS, 'form');
        if ($fakeRequest) {
            unset($GLOBALS['TYPO3_REQUEST']);
        }

at TYPO3\CMS\Form\Mvc\Persistence\FormPersistenceManager->__construct()
in typo3_src-12.4.23/typo3/sysext/core/Classes/Utility/GeneralUtility.php line 3016

        if (isset(self::$singletonInstances[$finalClassName])) {
            return self::$singletonInstances[$finalClassName];
        }
        // Create new instance and call constructor with parameters
        return new $finalClassName(...$constructorArguments);
    }

    /**
     * Returns the class name for a new instance, taking into account

at TYPO3\CMS\Core\Utility\GeneralUtility::makeInstanceForDi()
in typo3temp/var/cache/code/di/DependencyInjectionContainer_3245f89f7a65614df517973668a61cc9994d7f65.php line 13480

     * @return \TYPO3\CMS\Form\Mvc\Persistence\FormPersistenceManager
     */
    protected static function getFormPersistenceManagerInterfaceService($container)
    {
        return $container->services['TYPO3\\CMS\\Form\\Mvc\\Persistence\\FormPersistenceManagerInterface'] = \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstanceForDi(\TYPO3\CMS\Form\Mvc\Persistence\FormPersistenceManager::class, ($container->privates['TYPO3\\CMS\\Form\\Mvc\\Configuration\\YamlSource'] ?? self::getYamlSourceService($container)), ($container->services['TYPO3\\CMS\\Core\\Resource\\StorageRepository'] ?? self::getStorageRepositoryService($container)), ($container->services['TYPO3\\CMS\\Form\\Slot\\FilePersistenceSlot'] ??= \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstanceForDi(\TYPO3\CMS\Form\Slot\FilePersistenceSlot::class)), ($container->services['TYPO3\\CMS\\Core\\Resource\\ResourceFactory'] ?? self::getResourceFactoryService($container)), ($container->services['TYPO3\\CMS\\Form\\Mvc\\Configuration\\ConfigurationManager'] ?? self::getConfigurationManager2Service($container)), ($container->services['TYPO3\\CMS\\Core\\Cache\\CacheManager'] ?? self::getCacheManagerService($container)));
    }

    /**
     * Gets the public 'TYPO3\CMS\Form\Mvc\ProcessingRule' autowired service.

at DependencyInjectionContainer_3245f89f7a65614df517973668a61cc9994d7f65::getFormPersistenceManagerInterfaceService()
in typo3_src-12.4.23/vendor/symfony/dependency-injection/Container.php line 231

        try {
            if (isset($container->fileMap[$id])) {
                return /* self::IGNORE_ON_UNINITIALIZED_REFERENCE */ 4 === $invalidBehavior ? null : $container->load($container->fileMap[$id]);
            } elseif (isset($container->methodMap[$id])) {
                return /* self::IGNORE_ON_UNINITIALIZED_REFERENCE */ 4 === $invalidBehavior ? null : $container->{$container->methodMap[$id]}($container);
            }
        } catch (\Exception $e) {
            unset($container->services[$id]);

at Symfony\Component\DependencyInjection\Container::make()
in typo3_src-12.4.23/vendor/symfony/dependency-injection/Container.php line 211

    public function get(string $id, int $invalidBehavior = self::EXCEPTION_ON_INVALID_REFERENCE): ?object
    {
        return $this->services[$id]
            ?? $this->services[$id = $this->aliases[$id] ?? $id]
            ?? ('service_container' === $id ? $this : ($this->factories[$id] ?? self::$make ??= self::make(...))($this, $id, $invalidBehavior));
    }

    /**
     * Creates a service.

at Symfony\Component\DependencyInjection\Container->get()
in typo3_src-12.4.23/typo3/sysext/core/Classes/Utility/GeneralUtility.php line 2981

        // support classes that require dependency injection.
        // We operate on the original class name on purpose, as class overrides
        // are resolved inside the container
        if (self::$container !== null && $constructorArguments === [] && self::$container->has($className)) {
            return self::$container->get($className);
        }

        // Create new instance and call constructor with parameters
        $instance = new $finalClassName(...$constructorArguments);

at TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance()
in typo3_src-12.4.23/typo3/sysext/form/Classes/EventListener/DataStructureIdentifierListener.php line 103

        $dataStructure = $event->getDataStructure();
        try {
            // Add list of existing forms to drop down if we find our key in the identifier
            $formPersistenceManager = GeneralUtility::makeInstance(FormPersistenceManagerInterface::class);
            $formIsAccessible = false;
            foreach ($formPersistenceManager->listForms() as $form) {
                $invalidFormDefinition = $form['invalid'] ?? false;

at TYPO3\CMS\Form\EventListener\DataStructureIdentifierListener->modifyDataStructure()
in typo3_src-12.4.23/typo3/sysext/core/Classes/EventDispatcher/EventDispatcher.php line 42

        if ($event instanceof StoppableEventInterface && $event->isPropagationStopped()) {
            return $event;
        }
        foreach ($this->listenerProvider->getListenersForEvent($event) as $listener) {
            $listener($event);
            if ($event instanceof StoppableEventInterface && $event->isPropagationStopped()) {
                break;
            }
        }

at TYPO3\CMS\Core\EventDispatcher\EventDispatcher->dispatch()
in typo3_src-12.4.23/typo3/sysext/core/Classes/Configuration/FlexForm/FlexFormTools.php line 583

        $dataStructure = $this->ensureDefaultSheet($dataStructure);
        $dataStructure = $this->resolveFileDirectives($dataStructure);

        return $this->eventDispatcher
            ->dispatch(new AfterFlexFormDataStructureParsedEvent($dataStructure, $parsedIdentifier))
            ->getDataStructure();
    }

    protected function convertDataStructureToArray(string|array $dataStructure): array

at TYPO3\CMS\Core\Configuration\FlexForm\FlexFormTools->parseDataStructureByIdentifier()
in typo3_src-12.4.23/typo3/sysext/core/Classes/Configuration/FlexForm/FlexFormTools.php line 751

        // and substitute with a dummy DS.
        $dataStructureArray = ['sheets' => ['sDEF' => []]];
        try {
            $dataStructureIdentifier = $this->getDataStructureIdentifier($GLOBALS['TCA'][$table]['columns'][$field], $table, $field, $row);
            $dataStructureArray = $this->parseDataStructureByIdentifier($dataStructureIdentifier);
        } catch (InvalidParentRowException|InvalidParentRowLoopException|InvalidParentRowRootException|InvalidPointerFieldValueException|InvalidIdentifierException $e) {
        }

        // Get flexform XML data

at TYPO3\CMS\Core\Configuration\FlexForm\FlexFormTools->traverseFlexFormXMLData()
in typo3_src-12.4.23/typo3/sysext/core/Classes/Database/ReferenceIndex.php line 477

                            'softrefs' => [],
                        ];
                        // Create and call iterator object:
                        $flexFormTools = GeneralUtility::makeInstance(FlexFormTools::class);
                        $flexFormTools->traverseFlexFormXMLData($table, $field, $row, $this, 'getRelations_flexFormCallBack');
                        // Create an entry for the field:
                        $outRow[$field] = [
                            'type' => 'flex',
                            'flexFormRels' => $this->temp_flexRelations,

at TYPO3\CMS\Core\Database\ReferenceIndex->getRelations()
in typo3_src-12.4.23/typo3/sysext/core/Classes/Database/ReferenceIndex.php line 300

    protected function generateDataUsingRecord(string $tableName, array $record): array
    {
        $this->relations = [];
        // Get all relations from record:
        $recordRelations = $this->getRelations($tableName, $record);
        // Traverse those relations, compile records to insert in table:
        foreach ($recordRelations as $fieldName => $fieldRelations) {
            // Based on type
            switch ($fieldRelations['type'] ?? '') {

at TYPO3\CMS\Core\Database\ReferenceIndex->generateDataUsingRecord()
in typo3_src-12.4.23/typo3/sysext/core/Classes/Database/ReferenceIndex.php line 208

            $existingRecord = $this->getRecord($tableName, $uid);
            if ($existingRecord) {
                // Table has relation fields and record exists - get relations
                $this->relations = [];
                $relations = $this->generateDataUsingRecord($tableName, $existingRecord);
                if (!is_array($relations)) {
                    return $result;
                }
                // Traverse the generated index:

at TYPO3\CMS\Core\Database\ReferenceIndex->updateRefIndexTable()
in typo3_src-12.4.23/typo3/sysext/core/Classes/DataHandling/ReferenceIndexUpdater.php line 204

        foreach ($this->updateRegistry as $workspace => $tableArray) {
            $referenceIndex->setWorkspaceId($workspace);
            foreach ($tableArray as $table => $uidArray) {
                foreach ($uidArray as $uid) {
                    $referenceIndex->updateRefIndexTable($table, $uid);
                }
            }
        }
        $this->updateRegistry = [];

at TYPO3\CMS\Core\DataHandling\ReferenceIndexUpdater->update()
in typo3_src-12.4.23/typo3/sysext/core/Classes/DataHandling/DataHandler.php line 3599

                $hookObj->processCmdmap_afterFinish($this);
            }
        }
        if ($this->isOuterMostInstance()) {
            $this->referenceIndexUpdater->update();
            $this->processClearCacheQueue();
            $this->resetNestedElementCalls();
        }
    }

at TYPO3\CMS\Core\DataHandling\DataHandler->process_cmdmap()
in typo3conf/ext/container/Classes/Integrity/Sorting.php line 174

                            ],
                        ];
                        $datahandler->start([], $cmdmap);
                        $datahandler->process_datamap();
                        $datahandler->process_cmdmap();
                    }
                    $prevChild = $child;
                }
            }

at B13\Container\Integrity\Sorting->fixChildrenSorting()
in typo3conf/ext/container/Classes/Integrity/Sorting.php line 70

                $colPosByCType[$cType][] = $column['colPos'];
            }
            $this->unsetContentDefenderConfiguration($cType);
        }
        $this->fixChildrenSorting($containerRecords, $colPosByCType, $dryRun, $enableLogging);
        return $this->errors;
    }

    protected function unsetContentDefenderConfiguration(string $cType): void

at B13\Container\Integrity\Sorting->run()
in typo3conf/ext/container/Classes/Updates/ContainerMigrateSorting.php line 85

            }
            Bootstrap::initializeBackendAuthentication();
            $GLOBALS['LANG'] = GeneralUtility::makeInstance(LanguageServiceFactory::class)->createFromUserPreferences($GLOBALS['BE_USER']);
        }
        $this->sorting->run(false);
        return true;
    }

    public function getPrerequisites(): array

at B13\Container\Updates\ContainerMigrateSorting->executeUpdate()
in typo3_src-12.4.23/typo3/sysext/install/Classes/Service/UpgradeWizardsService.php line 275

                $performResult = true;
            }
        } else {
            // confirmation yes or non-confirmable
            $performResult = $wizard->executeUpdate();
        }

        $stream = $this->output->getStream();
        rewind($stream);

at TYPO3\CMS\Install\Service\UpgradeWizardsService->executeWizard()
in typo3_src-12.4.23/typo3/sysext/install/Classes/Controller/UpgradeController.php line 1099

        // ext_localconf, db and ext_tables must be loaded for the updates :(
        $container = $this->lateBootService->loadExtLocalconfDatabaseAndExtTables(false);
        $identifier = $request->getParsedBody()['install']['identifier'];
        $values = $request->getParsedBody()['install']['values'] ?? [];
        $messages = $container->get(UpgradeWizardsService::class)->executeWizard($identifier, $values);
        $this->lateBootService->resetGlobalContainer();
        return new JsonResponse([
            'success' => true,
            'status' => $messages,

**Comment by achimfritz** [comment]
Hi @topsnet-holgerd , looks not like a container bug? any other Extensions installed? (or Misconfiguration of EXT:forms ?)

**Comment by topsnet-holgerd** [comment]
Yes, maybe. Cause and effect sometimes are difficult in Typo3, I'm closing this issue now.
