### ISSUE TITLE
Do not check against TYPO3_MODE in ext_localconf.php

### ISSUE THREAD

**Issue by froemken** [b13/container#6]
Hello,

please remove condition against TYPO3_MODE in ext_localconf.php

Stefan

**Comment by mueller-sebastian** [comment]
Why would you do this?
https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ExtensionArchitecture/ConfigurationFiles/Index.html#best-practices-for-ext-tables-php-and-ext-localconf-php

**Comment by froemken** [comment]
He he. Nice. TYPO3 recommends it and does not recomments it:
https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.0/Important-82692-GuidelinesForExtensionFiles.html?highlight=typo3_mode

**Comment by ervaude** [comment]
Resolved with #18
