### ISSUE TITLE
Error on first install

### ISSUE THREAD

**Issue by maximaexchen** [b13/container#63]
I am very exited about this new approach!

But...

Installed container and container_example
Added a '2 Column Container With Header' to the page and got following error:

```
ERROR: Content Element with uid "1" and type "b13-2cols-with-header-container" has no rendering definition!
```

So in the typoscript is defined:
```
templateRootPaths {
        10 = EXT:container/Resources/Private/Contenttypes
    }
```
There is no such folder?

Or did I miss something?

Please update/precise the installation instruction.

**Comment by DanielWahl** [comment]
I have the same error. How did you fixed it?

**Comment by pixelbreit** [comment]
I have the same error with TYPO3 11.5.3 and Container 1.4.2.
I want to use it in my own Extension.
How did you fix it?

**Comment by maximaexchen** [comment]
@DanielWahl Sorry. Did not fix it. Decided not to use container.

**Comment by fnagel** [comment]
FYI: I had an typo in the TS config for my container element 🙈

**Comment by wineworlds** [comment]
`lib.contentElement` definition is missing
If EXT:fluid_styled content is not loaded, lib.contentElement must be defined by yourself.

```
lib.contentElement >
lib.contentElement = FLUIDTEMPLATE
lib.contentElement {
    templateName = Default
    templateRootPaths {
        0 = EXT:site_package/Resources/Private/Templates/Container/
    }
    partialRootPaths {
        0 = EXT:site_package/Resources/Private/Partials/Container/
    }
    layoutRootPaths {
        0 = EXT:site_package/Resources/Private/Layouts/Container/
    }
}
```

**Comment by nanna-dk** [comment]
Does not fix the error....
