### ISSUE TITLE
Support for Ext: content_defender "disallowed"

### ISSUE THREAD

**Issue by mixedpixels** [b13/container#70]
It would be great if not only "allowed" but also "disallowed" would be supported. Thus I can prevent an editor from putting a container CType inside a container CType. 
Very good extension, thanks for sharing!
Riona

![tt_content-php](https://user-images.githubusercontent.com/4137776/88154018-7f8c6980-cc06-11ea-95b8-32bb3727eff0.png)

**Comment by peterkraume** [comment]
This feature would be very helpful if you want to prevent editors to nest container elements.

**Comment by achimfritz** [comment]
we are working together with Nicole from EXT:content_defender to get a full Integration (without copy code from EXT:content_defender to EXT:container)

**Comment by peterkraume** [comment]
Awesome, much appreciated!
