### ISSUE TITLE
Problems with drag'n'drop

### ISSUE THREAD

**Issue by siegtob** [b13/container#71]
Since I have installed EXT:container, it is no more possible to drag content elements. No matter whether the elements are in- or outside a container element.

The log says:

> Core: Exception handler (WEB): Uncaught TYPO3 Exception: Argument 2 passed to B13\Container\Hooks\Datahandler\CommandMapPostProcessingHook::copyOrMoveChildren() must be of the type integer, string given, called in /public/typo3conf/ext/container/Classes/Hooks/Datahandler/CommandMapPostProcessingHook.php on line 49 | TypeError thrown in file /public/typo3conf/ext/container/Classes/Hooks/Datahandler/CommandMapPostProcessingHook.php in line 87. Requested URL: .../typo3/index.php?route=%%2Fajax%%2Frecord%%2Fprocess&token=--AnonymizedToken--&cmd[tt_content][29][move]=1&data[tt_content][29][colPos]=8-10&data[tt_content][29][sys_language_uid]=0

Otherwise I like the extension very much, good job, thanks!
Tobi

**Comment by achimfritz** [comment]
should be fixed in dev-master. can you test the master branch an confirm everything works?

**Comment by siegtob** [comment]
Yes, with the master-branch everything works fine!

**Comment by achimfritz** [comment]
i close this issue, 1.1.1 is released
