### ISSUE TITLE
[IMPROVMENT]: Make children-cols in frontend FLUIDTEMPLATE traversable

### ISSUE THREAD

**Issue by fgerards** [b13/container#82]
Hi,

right now, the B13\Container\DataProcessing\ContainerProcessor delivers 1-n "top-level" variables into the Fluid-Template (for example {children_101}, {children_102} etc.). This makes it hard to iterate over these columns to avoid repeating HTML-wrapping-markup. A fluidtemplate-variable like {containerColumns} that contains all the identified {children_*} elements would be nice.

Example for a traversable containerColumns variable in FLUIDTEMPLATE:
`<div class="section-teaser">
    <div class="max-width-container">
        <div class="flexcontainer teaser">
            <f:for each="{containerColumns}" as="child">
                <div class="flexbox-25">
                    <div class="flexbox-padding hero-boxes">
                        <f:format.raw>
                            {child.0.renderedContent}
                        </f:format.raw>
                    </div>
                </div>
            </f:for>
        </div>
    </div>
</div>`

**Comment by juergen-venne** [comment]
Would be great but the concept using a DataProcessor to get the children doesn't make this an easy task.
Assuming your children are named col1, col2...
You may use this construct to get the column count
```
<f:for each="{0:0,1:1,2:2,3:3,4:4,5:5,6:6}" as="count">
  <f:if condition="{col{count}}">
    <f:variable name="colCount" value="{count}" />
  </f:if>
</f:for>
```
Or iterate thru children by
```
<f:for each="{0:0,1:1,2:2,3:3,4:4,5:5,6:6}" as="count">
     <f:if condition="{col{count}}">
        <f:variable name="child" value="{col{count}}">
        from this point use the {child} variable
    </f:if>
</f:for>
```

**Comment by juergen-venne** [comment]
I created a pull request providing the ability to group cols to make them traversable.
https://github.com/b13/container/pull/109

**Comment by achimfritz** [comment]
closed due PR closed
