### ISSUE TITLE
[BUG] Moving records in workspaces

### ISSUE THREAD

**Issue by nstungcom** [b13/container#95]
Hi 👋 
while testing container with workspaces i might found a bug when moving records.

**Tested scenario:**
- Creating new CE in workspaces and moving them to check if it's working in BE & FE ✅ 
- Creating new container CE and move others CE inside & check if it's working in BE & FE ✅ 
- Creating new CE inside container and moving them & check if it's working in BE & FE ✅ 
- Moving CE **which were outside & not created inside**  of container CE & check if it's working in BE & FE ❌ 

The last scenario failed.

**Specs:**

- TYPO3 10 latest running in composer mode + PHP 7.4 using ddev
- container dev-master

I haven't found a solution yet and am still debugging, will report back when finding more.

#### Creating CE 38,39 in workspaces

|uid|pid|sorting|t3_origuid|t3ver_oid|t3ver_state|t3ver_count|t3ver_tstamp|t3ver_count|t3ver_move_id|colPos|tx_container_parent|
|---|---|-------|----------|---------|-----------|-----------|------------|-----------|-------------|------|-------------------|
|38 |1  |64     |0         |0        |0          |0          |0           |0          |0            |0     |0                  |
|39 |1  |128    |0         |0        |0          |0          |0           |0          |0            |0     |0                  |

#### After moving CE uid 39 above 38

|uid|pid|sorting|t3_origuid|t3_origuid|t3ver_oid|t3ver_state|t3ver_count|t3ver_tstamp|t3ver_count|t3ver_move_id|colPos|tx_container_parent|
|---|---|-------|----------|----------|---------|-----------|-----------|------------|-----------|-------------|------|-------------------|
|38 |1  |64     |0         |0         |0        |0          |0          |0           |0          |0            |0     |0                  |
|39 |1  |128    |0         |0         |0        |0          |0          |0           |0          |0            |0     |0                  |
|40 |1  |128    |39        |39        |39       |4          |0          |0           |0          |0            |0     |0                  |
|41 |1  |32     |0         |0         |0        |3          |0          |0           |0          |39           |0     |0                  |

#### After creating container CE (uid=42) and moving uid 38,39 in colPos 101

|uid|pid|sorting|t3_origuid|t3_origuid|t3ver_oid|t3ver_state|t3ver_count|t3ver_tstamp|t3ver_count|t3ver_move_id|colPos|tx_container_parent|
|---|---|-------|----------|----------|---------|-----------|-----------|------------|-----------|-------------|------|-------------------|
|38 |1  |64     |0         |0         |0        |0          |0          |0           |0          |0            |0     |0                  |
|39 |1  |128    |0         |0         |0        |0          |0          |0           |0          |0            |0     |0                  |
|40 |1  |128    |39        |39        |39       |4          |0          |0           |0          |0            |101   |42                 |
|41 |1  |32     |0         |0         |0        |3          |0          |0           |0          |39           |101   |42                 |
|42 |1  |96     |0         |0         |0        |1          |0          |0           |0          |0            |0     |0                  |
|43 |1  |96     |0         |0         |42       |-1         |0          |0           |0          |0            |0     |0                  |
|44 |1  |64     |38        |38        |38       |0          |0          |0           |0          |0            |101   |42                 |

#### After moving uid 39 above 38 in container CE same colPos but the sorting won't change

|uid|pid|sorting|t3_origuid|t3_origuid|t3ver_oid|t3ver_state|t3ver_count|t3ver_tstamp|t3ver_count|t3ver_move_id|colPos|tx_container_parent|
|---|---|-------|----------|----------|---------|-----------|-----------|------------|-----------|-------------|------|-------------------|
|38 |1  |64     |0         |0         |0        |0          |0          |0           |0          |0            |0     |0                  |
|39 |1  |128    |0         |0         |0        |0          |0          |0           |0          |0            |0     |0                  |
|40 |1  |128    |39        |39        |39       |4          |0          |0           |0          |0            |101   |42                 |
|41 |1  |32     |0         |0         |0        |3          |0          |0           |0          |39           |101   |42                 |
|42 |1  |96     |0         |0         |0        |1          |0          |0           |0          |0            |0     |0                  |
|43 |1  |96     |0         |0         |42       |-1         |0          |0           |0          |0            |0     |0                  |
|44 |1  |64     |38        |38        |38       |0          |0          |0           |0          |0            |101   |42                 |

#### Final tables

|uid|pid|sorting|t3_origuid|t3_origuid|t3ver_oid|t3ver_state|t3ver_count|t3ver_tstamp|t3ver_count|t3ver_move_id|colPos|tx_container_parent|
|---|---|-------|----------|----------|---------|-----------|-----------|------------|-----------|-------------|------|-------------------|
|38 |1  |64     |0         |0         |0        |0          |0          |0           |0          |0            |0     |0                  |
|39 |1  |128    |0         |0         |0        |0          |0          |0           |0          |0            |0     |0                  |
|40 |1  |128    |39        |39        |39       |4          |0          |0           |0          |0            |101   |42                 |
|41 |1  |0      |0         |0         |0        |3          |0          |0           |0          |39           |101   |42                 |
|42 |1  |96     |0         |0         |0        |1          |0          |0           |0          |0            |0     |0                  |
|43 |1  |96     |0         |0         |42       |-1         |0          |0           |0          |0            |0     |0                  |
|44 |1  |64     |38        |38        |38       |0          |0          |0           |0          |0            |101   |42                 |
|45 |1  |1      |0         |0         |0        |1          |0          |0           |0          |0            |102   |42                 |
|46 |1  |1      |0         |0         |45       |-1         |0          |0           |0          |0            |102   |42                 |
|47 |1  |2      |0         |0         |0        |1          |0          |0           |0          |0            |102   |42                 |
|48 |1  |2      |0         |0         |47       |-1         |0          |0           |0          |0            |102   |42                 |

**Comment by achimfritz** [comment]
i reduced the bug to:
* have an container in live WS with 2 CE in same colPos
* change to WS
* move second CE before first CE in Container
* reload page
* Error: frist CE is still at top

**Comment by achimfritz** [comment]
@nstungcom thanks for reporting, can you please test again?

**Comment by nstungcom** [comment]
@achimfritz Thanks for the fix, it work like a charm when moving CE in the same colPos in container. However when moving CE from lets say colPos 100 to 101 sometimes the problem restart 🙈  (container CE with 2 columns with colPos 100 and 101)

And also another problem show up when moving CE which were created in LIVE workspace to container CE they disappear in the BE and in the FE they are rendered outside of container CE.

To reproduce:

- Create 2 CE in LIVE workspace
- Switch to another workspace e.g. DRAFT
- Create container CE (in my case 2 columns with colPos 100 & 101)
- Moving the 2 CE which were created in LIVE workspace to container CE and reload (in my case colPos 100)
- The moved CE disappear in BE and rendered outside of container in FE

**Comment by achimfritz** [comment]
@nstungcom would you please test the master branch again?

**Comment by nstungcom** [comment]
@achimfritz sorry I was busy with works.

I can comfirm that when all CE's are created in DRAFT workspaces then everything is working fine.

But as long there are CE's mixed from LIVE workspace then it's not working:

- Moving CE's between colPos works (100 to 101) but the position can't be selected
- Moving CE's in the same colPos is not working (can't reorder the position)
- When previewing in FE the LIVE CE's is showing (which were moved to Container CE)

![Container-FE](https://user-images.githubusercontent.com/18316612/98797627-22166580-240d-11eb-95f3-8500064b7db8.JPG)

**Comment by achimfritz** [comment]
@nstungcom thanks for reporting, looks like core-bugs, i have create an issue on forge https://forge.typo3.org/issues/92849

**Comment by nstungcom** [comment]
@achimfritz thanks for the update. I'm so eager to try using container with working workspaces in the next project.

**Comment by achimfritz** [comment]
@nstungcom last bug should be fixed with https://forge.typo3.org/issues/92849, can you confirm

**Comment by nstungcom** [comment]
@achimfritz thanks for the great news. I can confirm that all the listed problems above are solved.
With the currently fixed issue [https://forge.typo3.org/issues/81208](https://forge.typo3.org/issues/81208), the next project with workspaces + container is not a dream anymore :wink:

Specs used/updated:
- TYPO3 10.4.17-dev running in composer mode + PHP 7.4 using ddev
